### PR TITLE
add mindspore tags

### PR DESCRIPTION
**Pull request by huxiaoman7**
Hi, I'm a developer of MindSpore, it is an all-scenario AI framework that was open-sourced in 2020, and I saw an issue in mindspore project:https://github.com/mindspore-ai/mindspore/issues/178 , 'AK391'  hopes me to add mindspore  Library to huggingface hub, so that I revise some code and hope to merge it into main branch.

### CODE REVIEW

**Comment by osanseviero** [comment]
Thanks @huxiaoman7 for this PR! Overall looks great, but at the moment there are no models with this tag - https://huggingface.co/models?other=mindspore, so introducing this change would create a filter that will lead to no models.

**Comment by huxiaoman7** [comment]
@osanseviero Thanks for your advice! I've already add mindspore tags on the model card as you said:https://huggingface.co/mindspore-ai/LeNet

**Comment by Wauplin** [comment]
Hi @huxiaoman7 (cc @omarespejel), I am doing a bit of cleaning in this repo's PR. What is the state of this one ?

I believe that since this PR has been opened, the documentation moved to [its own repo](https://github.com/huggingface/hub-docs). Could you please open a new PR there and close this one ? Thank you :) 
[This is the file to update](https://github.com/huggingface/hub-docs/blob/main/js/src/lib/interfaces/Libraries.ts).

**Comment by Wauplin** [comment]
Issue has been fixed in https://github.com/huggingface/hub-docs/pull/673 (`hub-docs` has been split from `huggingface_hub` repo). I'm closing this PR (without merging).

Inference widget is now available on the Hub for mindspore models.

**Pull request closed without merging**
