### PR TITLE
Sentence similarity for Spacy

### LINKED ISSUE #241: Add sentence similarity for spaCy
Computing similarity is simple with `spaCy` and there is an existing [template pipeline](https://github.com/huggingface/huggingface_hub/blob/main/api-inference-community/docker_images/common/app/pipelines/sentence_similarity.py) for sentence similarity at which can be modified for this. 

https://spacy.io/api/doc#similarity

### PR DESCRIPTION
**Pull request by devpramod**
This PR closes #241 by adding sentence similarity for spacy

### CODE REVIEW

**Comment by osanseviero** [comment]
Hi @devpramod! Thanks for this! Excited to see this out there!

A couple of quick things

* Could you make sure quality passes please? (`make quality`)
* Could you also add a GA workflow for `spaCy` by doing a copy of https://github.com/huggingface/huggingface_hub/blob/main/.github/workflows/python-api-espnet.yaml.

**Comment by devpramod** [comment]
Hi @osanseviero,
I did do `make quality`, I didn't see any changes though, as you can see below.

`black --check api_inference_community tests
All done! ✨ 🍰 ✨
11 files would be left unchanged.
isort --check-only api_inference_community tests
flake8 api_inference_community tests`

**Comment by osanseviero** [comment]
@devpramod by any chance did you add the wrong file? I see you added a `espnet` GA workflow, but not for `spacy` (the new file should be named `python-api-spacy.yaml`, and all uses of `espnet` should be renamed to `spacy` in the `yaml` file).

**Comment by devpramod** [comment]
@osanseviero I changed the GA Workflow for SpaCy. I see that `make style` and `make quality` are failing in the tests. When I run the commands It doesn't seem to be reformatting. I'm looking into the issue.

**Comment by osanseviero** [comment]
Related failing style/quality, you might have a different version.

Please make sure you have installed the correct versions by doing `pip install -e .[quality]` and retrying `make quality`

**Comment by devpramod** [comment]
Hi @osanseviero, I have fixed the code quality issue and the test is now passing.

**Pull request merged**
