### PR TITLE
Replace `ReprMixin` with dataclasses

### PR DESCRIPTION
**Pull request by mariosasko**
I've started working on https://github.com/huggingface/huggingface_hub/pull/1443 again. As part of it, I'm adding a `list_repo_tree` method to the API and would like to reuse `RepoFile` (and define `RepoFolder`) as types returned by it. However, I noticed that `RepoFile` as a `ReprMixin` object objects doesn't specify what attributes (of what type) it contains, has a weird string representation, and does not wrap the attributes with compatible types from the API (e.g. `SpaceRuntime` for `SpaceInfo`). So, I turned all the `ReprMixin` objects into dataclasses in a backward-compatible way to make working with them easier.

This should address https://github.com/huggingface/huggingface_hub/pull/951#discussion_r926474086. 

The API seems more stable nowadays, so I think the time is right to make this change. Dropping (less popular) attributes should still be fine even after this change.

### CODE REVIEW

**Comment by Wauplin** [comment]
Hey @mariosasko, thanks a lot for this big refacto/simplication of these objects! (and documentation)
I totally agree with you that dataclasses makes more sense than a custom `ReprMixin` (especially since we are already using dataclasses in a lot of cases). Using `self.__dict__.update(**kwargs)` as you did should make them forward-compatible even though it's not changing so often.

I saw that you dropped `.rfilename` in favor of `.path`. I'm fine with the change as it's more explicit and coherent with the rest of `huggingface_hub`. Just to be sure we don't break any script in the wild (there are some for sure), we should still add `def rfilename(self):` as a `@property` and trigger a deprecation warning when the property is used.

Other than that I don't have much comments yet to do. Please let me know when the PR is in a "ready" state and I'll do a more thorough review.

--- 

> This should address https://github.com/huggingface/huggingface_hub/pull/951#discussion_r926474086.

Digging into unresolved old comments :smile:

**Comment by julien-c** [comment]
> I saw that you dropped `.rfilename` in favor of `.path`. I'm fine with the change as it's more explicit and coherent with the rest of `huggingface_hub`. Just to be sure we don't break any script in the wild (there are some for sure), we should still add `def rfilename(self):` as a `@property` and trigger a deprecation warning when the property is used.

Yes it's important to keep backward compatibility and also it's the name of the attribute from the server API so better to not mask it IMO

**Comment by mariosasko** [comment]
@Wauplin `rfilename` is defined as an attribute of `RepoFile` in this line: https://github.com/huggingface/huggingface_hub/blob/5b8405a3940988f1cf82ab2f0be427c46e96bbf8/src/huggingface_hub/hf_api.py#L434

**Review by Wauplin — APPROVED** [review]
Looks good to me! Thanks for the high quality PR @mariosasko, it will really help making `huggingface_hub` more consistent. I have left a few comments but nothing major. Looks like you've already taken care of all the backward compatibility issues which is perfect :+

**Comment by Wauplin** [comment]
Thanks for making the changes @mariosasko! Failing tests are unrelated (CI is claky those days, working on it :confused:). So we're good to merge then :rocket:

**Pull request merged**
