### PR TITLE
Allow changing repo visibility programmatically

### PR DESCRIPTION
**Pull request by osanseviero**
Previous discussion in https://github.com/huggingface/huggingface_hub/issues/53

### CODE REVIEW

**Comment by julien-c** [comment]
lgtm but will wait for @LysandreJik to get an extra set of eyes

**Comment by julien-c** [comment]
Note: when CI fails for transient errors you should be able to relaunch it till it's green :)

**Comment by julien-c** [comment]
(not sure that's the case here though)

**Comment by osanseviero** [comment]
This is not a transient error, it seems to be an issue with the dataset tests. I'm checking everything works properly :)

**Review by LysandreJik — APPROVED** [review]
Nice, this is clean! LGTM

**Pull request merged**
