### PR TITLE
Enabling hf_transfer use.

### PR DESCRIPTION
**Pull request by Narsil**
This enables optional faster download using `hf_transfer`: https://github.com/huggingface/hf_transfer

- Only enabled is when using env variable `HF_TRANSFER=1` (makes it easy to disable).
- Disable other form of parallelism when using HF_TRANSFER (this might lead to threads slowing each other down).

With it enabled, the download might look "slow" because most of the time can be taken while moving from a tmpfs to actual disk the model files. 
This is deemed out of scope for now.

hf_transfer provides no feedback during download, again this can be added later if we want to grow the spec for this.

### CODE REVIEW

**Comment by Narsil** [comment]
@Wauplin I can safely ignore codecov right ?

**Comment by Wauplin** [comment]
> @Wauplin I can safely ignore codecov right ?

Yes no worries !

**Review by Wauplin — COMMENTED** [review]
Hey @Narsil, following up on your PR. I made a few changes (renamed the env variable to HF_HUB_ENABLE_HF_TRANSFER, mentioned it in the docs and added more debug info).
I tested it locally and got a 1.3x speed up when downloading [this file](https://huggingface.co/gpt2/blob/main/64-8bits.tflite) but as said in the call, my bottleneck is the network bandwith anyway.

Otherwise PR looks good to me now. Will wait from other reviews here.

**Comment by LysandreJik** [comment]
I don't have any problems regarding the implementation. Still, I'm not too sure about adding an optional rust dependency for a speedup that seems to affect setups with high-speed bandwidth links (if I understand correctly from the internal comments). Is the idea that we would only use this internally?

I don't think it would have community usage anyway, given that it would be particularly useful for larger artifacts, and I would think progress bars are imperative to large downloads as they would otherwise feel like shooting in the dark.

**Comment by julien-c** [comment]
yes my understanding is this is mostly (or only) for internal use (Inference API notably)

**Comment by Wauplin** [comment]
As I see it, this is mostly for internal purposes. I have documented it only at 1 place in an "advanced" section and with warnings on the fact that it's "experimental" (understand "use it if you want but don't complain"). I don't think we will ever promote it out loud but having it is still relevant IMO

**Comment by Narsil** [comment]
I would like also to mention @apolinario which thinks it could be very useful for Spaces (People tend to include the model files directly in the space because it's faster, but putting strain on the spaces infra as far as I understand).

The caveat for spaces, is that by default for CPU there is a `limits:cpu` which caps CPU usage and throttles `hf_transfer` which leads to similar or slower download speeds. But for all GPU and CPU upgrades, there is a benefit.
If you want to check out https://huggingface.co/spaces/Narsil/hf_transfer_showcase

Clearly the biggest win was this anyway: https://github.com/huggingface/huggingface_hub/pull/1267

**Comment by LysandreJik** [comment]
Ok in that case, if you feel strongly and think it won't hut maintenance @Wauplin, let's merge it in!

**Comment by Wauplin** [comment]
Let's merge it then :)

**Pull request merged**
