### PR TITLE
Explicitly fail on Keras3

### PR DESCRIPTION
**Pull request by Wauplin**
This PR makes the helpers `save_pretrained_keras` and `load_pretrained_keras` explicitly fail if called with Keras 3 installed. The Keras x HF integration implemented in `huggingface_hub` is outdated and therefore not suitable for Keras 3 models. At least 2 parts broke with the Keras 2 -> 3 migration:
- load model expects a file path instead of a folder path (as reported in https://github.com/huggingface/huggingface_hub/pull/2104 by @ZhanPascal)
- `model.history` doesn't exist anymore (fails when saving model) 

For the record, Tensorflow 2.16 has been release last week (7th March 2024) and introduces the breaking change of making Keras3 the default keras version. This makes our tests fail in the CI so I've pinned the versions to install TF2.15 and Keras2 when running the tests.

Of course,  this PR is a temporary fix to explicitly fail on version incompatibilities but **the goal is to foster the Keras x HF integration even further.**  Official support for Keras3 models is the objective.

Ping @Rocketknight1 as well for Keras discussions.

---

In the meantime, the integration can be handled like this:

```py
# instead of 'save_pretrained_keras' / 'push_to_hub_keras'
import tensorflow as tf
from huggingface_hub import upload_folder

tf.keras.models.save_model(model, save_directory)
upload_folder(save_directory)
```

```py
# instead of 'from_pretrained_keras'
import tensorflow as tf
from huggingface_hub import hf_hub_download

path = hf_hub_download("<repo_id_on_the_hub>", filename="model.keras")  # adapt repo_id and filename
model = tf.keras.models.load_model(path)
```

Those 2 workarounds don't include semi-automatic model cards or saving model history but should do the trick for most use cases.

### CODE REVIEW

**Comment by osanseviero** [comment]
FYI @merveenoyan who worked in the initial implementation

**Comment by Rocketknight1** [comment]
LGTM! One comment is that TF has a compatibility package `tf-keras`, to allow you to use the Keras 2 API with TF >= 2.16. As a result, you might want to change the check so that it doesn't fail in cases when Keras 3 is installed, but the user is using `tf-keras`. See the section of the release notes [here](https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1) that starts with "To continue using Keras 2.0"

**Comment by Rocketknight1** [comment]
It might be easier to check for methods/attributes on the model itself? Several of those changed name with Keras 3.

**Comment by Wauplin** [comment]
@Rocketknight1 I've slightly updated the PR. Now behavior is:
- when loading keras model, check for either `tf_keras` or `tf.keras`
- when saving keras model, check if model is in keras 3 (hackily based on model attributes). If Keras 3 => raise exception. 

Should handle cases correctly now, including if keras2 and keras3 are installed at the same time.

**Review by LysandreJik — APPROVED** [review]
Yes, this looks good to me! Maybe good if @Rocketknight1 can confirm if this is the behavior he had in mind.

**Review by Rocketknight1 — APPROVED** [review]
Yes! Checking for a missing `history` attribute is a good way to detect Keras 3 models without needing imports.

**Comment by Wauplin** [comment]
Thanks @LysandreJik @Rocketknight1 for the review and confirming the approach is correct. Ready to be merged then :)

**Pull request merged**
