### PR TITLE
Refactor create_repo

### PR DESCRIPTION
**Pull request by SBrandeis**
cc @osanseviero

### CODE REVIEW

**Review by julien-c — APPROVED** [review]

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks @SBrandeis

**Comment by SBrandeis** [comment]
What's the ETA on releasing this?

**Comment by LysandreJik** [comment]
When do you need it? We can do a release now if you need it fast

**Comment by SBrandeis** [comment]
The faster the better :)

**Pull request merged**
