### PR TITLE
Upgrade Espnet to latest community and use main repo

### PR DESCRIPTION
**Pull request by osanseviero**
This change fixes espnet inference since it was using an experimental fork before.

### CODE REVIEW

**Review by Narsil — APPROVED** [review]
LGTM. Models being slow is acceptable.

Maybe let's just add a comment so future testers won't be too surprised.

**Comment by osanseviero** [comment]
The slowness issue is now fixed! Will merge this tomorrow. I did a copy of the GA workflow but it will be merged with the AllenNLP one in a follow-up

**Comment by Narsil** [comment]
Nice, where is the slowness fix, can't find it here ?

**Comment by osanseviero** [comment]
We now specify `beam_size=1` in ASR which makes inference considerably faster

**Pull request merged**
