### PR TITLE
Updates types for RepoCards fields 

### PR DESCRIPTION
**Pull request by davanstrien**
Follows up from #1356 to update more repo card attribute types to `Optional[List[str]]`. 

@Wauplin @julien-c, at the moment, I have changed the types for:
- metrics 
- language 
- source datasets

For some attributes like `license`, it's likely that it will almost only be a single string: should I also change those types or focus only on the fields more likely to be an array with multiple items?

### CODE REVIEW

**Comment by Wauplin** [comment]
Hi @davanstrien , thanks for taking the time.

> For some attributes like license, it's likely that it will almost only be a single string: should I also change those types or focus only on the fields more likely to be an array with multiple items?

Yes I think it makes sense to keep the type `str` for fields where a single values is very likely to happen. `license` is the case but maybe `language` as well, isn't it?

**Comment by julien-c** [comment]
i think the current PR is good! (i was not sure about languages either, but i think it's fine to type it as str[])

**Comment by Wauplin** [comment]
Fine with keeping the PR as is it as well, was just asking.

**Comment by davanstrien** [comment]
Thanks both; I'll do a quick double-check for any other changes tomorrow am. I'll update the PR to ready for review once I've done that.

**Comment by davanstrien** [comment]
I updated the `source_datasets` field to `List[str]`. I think this is ready to review/merge.

**Review by Wauplin — APPROVED** [review]
Looks good to me! I'm merging it :)

**Pull request merged**
