### PR TITLE
Fix raise syntax: remove markdown bullet point

### PR DESCRIPTION
**Pull request by mishig25**
There were extra markdown bullet points in `Raise` docstrings

which is causing UI bug: 
image

### CODE REVIEW

**Comment by mishig25** [comment]
https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_1034/en/package_reference/hf_api#huggingface_hub.HfApi.create_commit for demo

**Comment by Wauplin** [comment]
Cool, thanks for taking care of it. CI is failing but I don't get why. I rerun it just to see if it was a temporary problem.

**Comment by mishig25** [comment]
@Wauplin rerun the CI, and all of them except `codecov/project` are passing. Should I merge it?

**Review by Wauplin — APPROVED** [review]

**Comment by Wauplin** [comment]
Great, I guess we'll never know why it was failing. I approved and merged :)

**Pull request merged**
