### PR TITLE
[Spaces] Debian packages.txt

### PR DESCRIPTION
**Pull request by cbensimon**

### CODE REVIEW

**Comment by osanseviero** [comment]
This is very cool, there were some people from the Flax event asking about this. We need to find out a way to announce these changes.

Could there be a changelog modal or something in https://huggingface.co/spaces?

**Comment by julien-c** [comment]
Maybe just a top banner like on the homepage, with the latest change + link to a changelog subsection in this doc? WDYT?

**Comment by julien-c** [comment]
Do you want to take a stab at it?

**Review by julien-c — APPROVED** [review]

**Comment by cbensimon** [comment]
Linking https://github.com/huggingface/huggingface_hub/pull/257

**Pull request merged**
