### PR TITLE
Add datasets filtering and sorting

### PR DESCRIPTION
**Pull request by lhoestq**
For consistency with `list_models()`, allow to filter and sort the datasets in `list_datasets()`

I added these parameters:
- filter
- sort
- direction
- limit

Before merging: 
We still need to merge some PRs that are currently under review in the backend to support:
- filtering multiple tags
- direction & limit

### CODE REVIEW

**Comment by lhoestq** [comment]
PRs are merged in the backend, just waiting for the new API to be deployed on the website

**Comment by Pierrci** [comment]
@lhoestq it's deployed, lmk if you encounter any problem.

**Review by LysandreJik — APPROVED** [review]
:heart:

**Comment by lhoestq** [comment]
It's all good thanks :)

**Pull request merged**
