### PR TITLE
Don't pull to same directory for push_to_hub in mixin

### PR DESCRIPTION
**Pull request by osanseviero**
The current approach clones the repo to the same directory as where the files where saved, which leads to files unexpectedly appearing when pushing to hub. Also, if you then delete files cloned files locally, they are deleted in the remote repo.

This change is consistent with what is done in transformers [implementation](https://github.com/huggingface/transformers/blob/a55dc157e3667b7c1e8696fbbb5d94df46e7a354/src/transformers/file_utils.py#L1959)

### CODE REVIEW

**Comment by julien-c** [comment]
> which leads to files unexpectedly appearing when pushing to hub

Which files?

**Comment by julien-c** [comment]
FWIW the transformers implementation might change because it seems weird to me to clone to a temp dir – we should just store everything into a git-versioned directory that's the user's current working copy. (like you would do with code)

**Comment by osanseviero** [comment]
> Which files?

If you have a repo in the Hub, add a model card in the browser, and then you use `push_to_hub`, the existing implementation will clone the model card to your local directory, which is not what `push_to_hub` should do IMO. I would rather have an implementation closer to the transformers [PushToHubMixin](https://github.com/huggingface/transformers/blob/d3eacbb8299161d21e007e7e3d42505dae741282/src/transformers/file_utils.py#L1904)

> FWIW the transformers implementation might change because it seems weird to me to clone to a temp dir – we should just store everything into a git-versioned directory that's the user's current working copy. (like you would do with code)

I think users should be able to do both

1. Simply push directly to the Hub without creating local files or directories
`model.push_to_hub("my_repo_name")`

2. Push to the Hub from an existing directory, which is closer to the existing implementation (which uses a staticmethod and really unrelated to the model class)
`model.push_to_hub("my-local-directory-nam", "my_repo_name")`

But imo, if what a user wants to do is 2, I don't see much of the value of the mixin. The `push_to_hub` is unrelated to the `model` object, could be used to upload any directory, and I would instead suggest to use `Repository` and its `push_to_hub` method which would already fit in "store everything into a user-accessible, git-versioned directory that's the user's current working copy"

**Comment by julien-c** [comment]
> If you have a repo in the Hub, add a model card in the browser, and then you use push_to_hub, the existing implementation will clone the model card to your local directory, which is not what push_to_hub should do IMO.

I think generally (ie. not talking specifically about the mixin here) this is consistent with git and actually a desirable behaviour (you need to pull before push)

> Simply push directly to the Hub without creating local files or directories

Yes, why not (though it's obfuscating git a little bit and I'm not sure it's super useful – why wouldn't you want to also store  locally?). This should probably not be named `push_to_hub` though, but something else, as `push_to_hub` was the name of the method from `Repository`

> But imo, if what a user wants to do is 2, I don't see much of the value of the mixin. The push_to_hub is unrelated to the model object, could be used to upload any directory

Yes, I kinda agree. I think the "main" API in the mixin was actually supposed to be `model.save_pretrained(..., push_to_hub=True)` and not this low-level one

maybe it's just a `save_to_hub` method that doesn't store anything locally (only in tmp) then. Again not sure this is super useful

Tagging @sgugger and @LysandreJik with whom we've had similar recent discussions

**Comment by osanseviero** [comment]
Closing this based on previous discussions and direction from `transformers`  😄

**Pull request closed without merging**
