### PR TITLE
Robustify CI

### PR DESCRIPTION
**Pull request by julien-c**

### CODE REVIEW

**Comment by julien-c** [comment]
champagne

**Comment by julien-c** [comment]
Ok @LysandreJik this passes (CI could not pass before, there was an obsolete apiToken) but I'm not adventurous enough to relaunch with another empty commit =)

**Comment by julien-c** [comment]
green again

**Comment by LysandreJik** [comment]
Incredible :champagne:

**Review by LysandreJik — APPROVED** [review]
Looks fantastic to me

**Pull request merged**
