### PR TITLE
Reformat repo README

### PR DESCRIPTION
**Pull request by osanseviero**
This changes the main repo README to be more relevant and throw less info to the readers.

A big chunk was copy-pasted to huggingface_hub/src/README.md. That README should be updated in a follow-up PR with  other pointers.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Cool! How about using this opportunity to do the screenshots with the new front?

**Comment by LysandreJik** [comment]
I would also put links to all documentation READMEs

**Comment by osanseviero** [comment]
I replaced the images and added reference to `docs`.

**Review by LysandreJik — APPROVED** [review]
LGTM

**Pull request merged**
