### PR TITLE
1025  `huggingface-cli delete-cache` command

### PR DESCRIPTION
**Pull request by Wauplin**
Solve https://github.com/huggingface/huggingface_hub/issues/1025.

This PR add a `huggingface-cli delete-cache` command to free up some space. For now it has no options at all but the goal (as discussed in https://github.com/huggingface/huggingface_hub/issues/1025 is to have several options to ease the UX). Those options can be addressed in separate PRs.

This command is based on [`InquirerPy`](https://github.com/kazhala/InquirerPy) to build the multiselect menu in the terminal. This dependency has to be installed with `pip install huggingface_hub[cli]`. Since we want to avoid as much as possible cross-platform issues, I chose a library that is built on top of [`python-prompt-toolkit`](https://github.com/prompt-toolkit/python-prompt-toolkit) which seems to be a reference to build a TUI form. I have added in comments other options that I chose not to use (with reasons).

**Demo:**
[Screencast from 12-09-2022 18:25:54.webm](https://user-images.githubusercontent.com/11801849/189706622-697ccc60-515b-4960-ad97-b7df2bf5b6c6.webm)

**EDIT:**
I have added a `--disable-tui` flag for platform that doesn't support/have not installed InquirerPy. When used, the manual review happens in a temporary file. The user is asked to manually review and edit the file and then continue the process. It is a less convenient than the multiselect menu (as an external editor is used) but offers exactly the same features to the user.

**TODO:**
- [x] implement a first `huggingface-cli delete-cache` command
- [x] implement the `--disable-tui` flag 
- [x] test the command line
- [x] test the TUI (as much as possible ?)
- [x] test then non-TUI part
- [x] documentation

---

~Note: Built on top of https://github.com/huggingface/huggingface_hub/pull/1045 to have the time stats for deletion. I'll rather merge https://github.com/huggingface/huggingface_hub/pull/1045 first and and take care of the conflicts myself.~ It's merged :)

### CODE REVIEW

**Comment by Wauplin** [comment]
PR is ready to be reviewed. I added the `--disable-tui` flag for user that can't have the terminal interface running on their machine. 

I also completed the tests and the documentation :)

**Review by LysandreJik — APPROVED** [review]
Very impressive PR! This looks good to me. Very cool to play with.

I played with it manually but I didn't review the code in depth given the number of changes. Fine to me to merge as is given that it doesn't touch anything critical.

**Comment by Wauplin** [comment]
Thanks @LysandreJik for taking care of reviewing and testing it !
I had to say I felt that the PR was too big but didn't know how to split it correctly.... :grimacing: Let's iterate if we have issues.

**Comment by stas00** [comment]
Just tried it out - works awesome! thank you, @Wauplin!

May I just suggest that it could use a default sorting that is conducive to clean up? I'd say size or age would be the most important criteria. Alphabetical order is of no value.

I'd say age is probably the most important one when purging cache.

Thank you!

**Pull request merged**
