### PR TITLE
Run GA on forks

### PR DESCRIPTION
**Pull request by LysandreJik**
This PRs completes the GA workflows so that Github Actions may run on forks. (This PR is opened from a fork)

### CODE REVIEW

**Review by julien-c — APPROVED** [review]
Forgot to approve this. Thanks!

**Comment by LysandreJik** [comment]
My pleasure!

**Comment by julien-c** [comment]
The (small) drawback of this is that it seems to run all test suites twice when you push a commit to a PR branch

see https://github.com/huggingface/huggingface_hub/pull/25 

> 8 successful checks

**Comment by LysandreJik** [comment]
Oops, this is because I forgot something. Let me open a PR that fixes this.

**Pull request merged**
