### PR TITLE
change metadata key from `finetuned_from` to `base_model`

### PR DESCRIPTION
**Pull request by julien-c**
related to:
- https://github.com/huggingface/hub-docs/pull/1084
- https://github.com/huggingface/moon-landing/issues/7584
- https://github.com/huggingface/moon-landing/pull/7350
- https://github.com/huggingface/moon-landing/pull/7989

### CODE REVIEW

**Review by Wauplin — APPROVED** [review]
Looks good! I don't expect it to break anything in the wild.

**Comment by julien-c** [comment]
(context: https://github.com/huggingface/transformers/pull/24528#issuecomment-1613022119)

**Comment by LysandreJik** [comment]
cc @muellerzr on aligning on this between the two libraries eventually

**Comment by julien-c** [comment]
For diffusers, it's weird that they don't use a `base_model`, they're supposed to output it in their model card no? cc @patrickvonplaten maybe

**Comment by Wauplin** [comment]
If it can help, I was mentioning this part of the code: https://github.com/huggingface/diffusers/blob/64603389da01082055a901f2883c4810d1144edb/src/diffusers/utils/hub_utils.py#L125.

**Comment by julien-c** [comment]
maybe raise this question in a diffusers slack channel

**Comment by Wauplin** [comment]
(link to -internal- [thread](https://huggingface.slack.com/archives/C03HBN1C8CW/p1699290863016789))

**Review by davanstrien — COMMENTED** [review]
LGTM

**Pull request merged**
