### PR TITLE
Fix AllenNLP QA example

### PR DESCRIPTION
**Pull request by epwalsh**

### CODE REVIEW

**Comment by LysandreJik** [comment]
Thanks @epwalsh!

**Review by osanseviero — APPROVED** [review]
Thank you @epwalsh! 

I think the same bug might be in the Inference API. If possible, could you update the code in the docker image (just this [line](https://github.com/huggingface/huggingface_hub/blob/main/api-inference-community/docker_images/allennlp/app/pipelines/question_answering.py#L14))? If not, we're happy to send a follow-up PR

**Comment by LysandreJik** [comment]
The inference-api will also need to be updated to use a more recent version of AllenNLP; right now it's using an old fork of mine (hence why it works without the `hf://`), it should probably just use the latest version available and pin it. It's done in the AllenNLP requirements: https://github.com/huggingface/huggingface_hub/blob/main/api-inference-community/docker_images/allennlp/requirements.txt

cc @Narsil

**Comment by epwalsh** [comment]
@LysandreJik, thanks, I'll update that as well 👍

**Comment by osanseviero** [comment]
Thank you!

**Pull request merged**
