### PR TITLE
Remove deprecated `list_repos_objs` and `huggingface-cli repo ls-files`

### PR DESCRIPTION
**Pull request by julien-c**
Follow-up to deprecation in #510 and e618f6127249ad3a1f4862281dc0b947645dd3e3

The server endpoint is getting removed from the hub as we speak (cc @coyotte508 @XciD)

### CODE REVIEW

**Comment by julien-c** [comment]
CI is flaky but all tests pass

**Review by osanseviero — APPROVED** [review]
Nice :rocket:

**Review by LysandreJik — APPROVED** [review]
OK, LGTM

**Comment by julien-c** [comment]
thanks for approving!

**Pull request merged**
