### PR TITLE
[doc] org-cards

### PR DESCRIPTION
**Pull request by julien-c**

### CODE REVIEW

**Comment by osanseviero** [comment]
Isn't `docs/assets/hub/org-card.png` too large? (1.6MB)

**Comment by julien-c** [comment]
Oops yeah you're probably right. I shouldn't have rushed... 🙈

**Comment by julien-c** [comment]
sorry i rushed this and merged, still interested in a quick review though

**Comment by stevhliu** [comment]
Thanks for adding this! Two suggestions:

1. Would it be better if we showed an image of a more complete org card - like [Amazon's](https://huggingface.co/amazon) - to showcase what you can do in the org card (i.e., have links to a video, blog, and docs)? 
2. I think maybe we should also mention that you need to know some HTML to style the org card so users know what to expect ahead of time.

Otherwise, it looks great! I love the button on the top right of the org card that links to the docs 👍

**Comment by julien-c** [comment]
my hunch is that most users are just going to write some markdown text and not really bother with complicated HTML, wdyt @osanseviero? (that's why I added a simpler example as the first example)

But yeah you're right we can add a sentence or paragraph about being able to write HTML inside the .md file, do you want to open a PR?

**Comment by osanseviero** [comment]
(Note that Amazon's card does not really play the video, it just redirects to YT.) 

re: used image. I think as-is is fine. Note we link to the more complex org cards right below, so it's up to the users if they want to investigate more complex org cards.

I agree some additional info on writing HTML would be useful!

**Pull request merged**
