### PR TITLE
Upgrade HTTP Client Requests

### PR DESCRIPTION
**Pull request by Ousret**
Hello fellow maintainers,

I'm presenting this PR as a discussion starting point for a potential improvement.
First of all, I know, this looks like an unexpected journey! But hopefully, it will be a great ending.

**Synopsis**

For many years now, Requests has been frozen and blocked millions of developers, left in a vegetative state regarding evolutions in the field.

It is time that change came from ourselves.

Let me introduce you to [Niquests](https://github.com/jawah/niquests). The level up with HTTP interactions for Python we deserve.

**What do we gain?**

There are a ton of pros, Among them, you'll find:

- Plain better security
- Resilience to most firewall/fingerprinting
- True support for HTTP/2, and HTTP/3
- Multiplexed connection (get up to 3X faster throughput)
- Built-in support for Async
- Faster
- No more Certifi, finally access to your OS Trust Store
- More reliable and compliant to standards
- No more Python httplib for HTTP/1.1
- Fully backward compatible

**What does this PR change?**

The PR starts with a drop-in replacement that involves next to zero changes.

**What are the next steps?**

If you are open to thinking about this, we may have those tasks ahead:

~needed to have a mergeable PR~ :heavy_check_mark: 

- ~Fix some mypy complaints~
- ~Fix the small amount of tests that started to fail, should be trivial~

_after, on a different topic, probably other PRs_

- Simplify some code path where it can be (leverage new included features)
- Drop aiohttp, no longer required for AsyncInferenceClient
- Fully leverage the multiplexed connection
- Unlock full multithreading capabilities if needed

Hopefully, you'll consider this, I, for myself am ready to answer any of your concerns.

<small>Niquests is made in :fr: !</small>

### CODE REVIEW

**Comment by Wauplin** [comment]
Hey @Ousret! Sorry for the late reply. First of all, congratulations for the impressive work done in `niquests`! Taking over `requests` legacy is a huge task and I wish the best for this project to succeed.

Regarding the PR itself, thank you for taking the time to open it. Changing the HTTP backend of `huggingface_hub` is a big step we have in mind but we don't want to make it right now. In particular, it will not happen before the `1.0` release (that we are not planning yet). `huggingface_hub` is the backend library for a lot of ML libraries out there, used by millions of developers every day. Therefore we are extra careful when updating any dependency and `requests` might be the trickiest one. A first concern is how to deal with stuff like `try: ... except requests.HTTPError ...` in the wild but the question is broader than that. If we were to move away from `requests`, we would go for a solution that has already a strong community and a few years of proven track record. 

To make it short, I don't think we will switch to `niquests` in the near future. This has nothing to do with the quality of the work done in it but the fact that we favour minimal friction over optimized performances. I think that other projects are more suitable to be first adopters of `niquests`, especially the ones that are not used as dependencies themselves.

**Comment by Wauplin** [comment]
Out of curiosity btw, why the name `niquests`? Is it for "not `requests`"? :smile: 
And what are the main differences compared to `httpx`?

**Comment by Ousret** [comment]
Re:

Thank you for the response.

> Taking over requests legacy is a huge task and I wish the best for this project to succeed.

(i) Yes! (ii) We, both.

 > A first concern is how to deal with stuff like try: ... except requests.HTTPError ... in the wild

Excellent question, this is pretty easy to handle gracefully.

We are facing two immediate scenarii:

- I don't have requests in my environment

We have to inject a mirror (or pointer if you prefer) of niquests in requests. So that it remains transparent.

- I have requests in my environment

Simply have a hybrid exception class that will permit you to catch it transparently. (e.g. `class RequestCompat(NiquestsErr, RequestsErr)` and do the transposition inside of the project.

Finally,

If I am not mistaken, your user base might want to catch your internal exception class instead of the one from requests.

 > If we were to move away from requests, we would go for a solution that has already a strong community and a few years of proven track record.

From a philosophical standpoint, it does not make sense :smile: 
As developers, we should act as scientists, not as inertias machines. Is a physics law right due to its massive user base or by... simply being true?

It's a paradox that simply blocks diversity. I don't know about Huggingface recruiting process, but I never actually read the "years of experience" mention in the CV until I assessed what X can bring to our company. I'd like to see that in open-source someday.
I truly think that a careful methodology can outweigh this thinking.

> This has nothing to do with the quality of the work done in it but the fact that we favour minimal friction over optimized performances.

I understand. 
Ough by curiosity, isn't possible to present this as an optional alternative HTTP backend? This would be minimal friction.

> Out of curiosity btw, why the name niquests? Is it for "not requests"? 😄

I am neither going to affirm it nor deny it, I'd prefer letting this to the user's interpretation.

> And what are the main differences compared to httpx?

There's a significant amount of difference, the first being to truly leverage the protocol's capabilities. e.g. multiplexing.
For another, it is a drop-in replacement of Requests, and the major parts of Requests user base are reluctant to re-learn what is a basic principle. So I am counting on this.
You can find the exhaustive list of what is offered in the repository.

So, feel free to close/archive this PR anytime.
But if you, for whatever reason, want to work on something, don't hesitate to ping me.

**Comment by Wauplin** [comment]
> Finally, if I am not mistaken, your user base might want to catch your internal exception class instead of the one from requests.

Yes I would like users to do that but I'm pretty confident they don't and continue to catch `requests` errors.

> From a philosophical standpoint, it does not make sense 😄
As developers, we should act as scientists, not as inertias machines. Is a physics law right due to its massive user base or by... simply being true?
> It's a paradox that simply blocks diversity. I don't know about Huggingface recruiting process, but I never actually read the "years of experience" mention in the CV until I assessed what X can bring to our company. I'd like to see that in open-source someday.

I agree with you that open-source must be a good place to experiment things. However, my thinking when trying new dependencies depends a lot on the context:
- as a developer prototyping a new tool, I would consider using the latest libraries available, check which one can fit my use case and experiment with it
- as a developer working on an internal tool, I would be a bit more careful on the dependencies of my project to be sure it's robust-enough and well maintained. Since I own the stack of the internal tool, making a switch from lib A to lib B and vice-versa is manageable so I would be more willing to experiment.
- as a maintainer working on largely used library, I mostly care on keeping the project as stable as possible even if that means less optimizations and slower iteration cycles. I don't own the environment in which users will install the library, which limits to possibilities for experimenting. I also don't own the code that will use my library so I need to keep breaking changes as limited as possible.

> There's a significant amount of difference, the first being to truly leverage the protocol's capabilities. e.g. multiplexing.
For another, it is a drop-in replacement of Requests, and the major parts of Requests user base are reluctant to re-learn what is a basic principle. So I am counting on this.
You can find the exhaustive list of what is offered in the repository.

Understood, thanks!

> So, feel free to close/archive this PR anytime.
But if you, for whatever reason, want to work on something, don't hesitate to ping me.

Thanks again for the work and for the information. I will close this PR for now. If we ever go back to switching the HTTP backend, I will let you know.

**Pull request closed without merging**
