### PR TITLE
Set correct permissions on blob file

### LINKED ISSUE #1141: Permission on local cached files should be configurable
**Is your feature request related to a problem? Please describe.**
If multiple users attempt to share the same models cache (e.g., on a company internal shared file system), anytime model files are downloaded, their permissions are 0600 (on linux) regardless of the umask. This is because file_download is using `tempfile.NamedTemporaryFile` (see https://github.com/huggingface/huggingface_hub/blob/60077db55b81f2add3fd3bf774d7dc0f7acc4857/src/huggingface_hub/file_download.py#L727 and https://stackoverflow.com/questions/10541760/can-i-set-the-umask-for-tempfile-namedtemporaryfile-in-python), so only the user who downloaded them can read those files. As a result, users can't share a local cache, which is a waste of resources and time for users.

**Describe the solution you'd like**
huggingface_hub should `chmod` the downloaded files (for example, using the current `os.umask`, or using a new configuration option) after the file is downloaded and before it is renamed so it can be shared across users.

**Describe alternatives you've considered**
Separate caches per user is a workaround but is a massive waste of disk space and time. Each user would have to wait for new downloads even if the files have been downloaded by another user already.

**Additional context**
Trying to use the HuggingFace diffusers/transformers library in an enterprise context.

### PR DESCRIPTION
**Pull request by Wauplin**
Fix #1141 #1215.

Workaround I used is to infer umask from the permission set on the `blobs/` folder. This is not optimal (not getting the umask from the user directly) but good enough as at least all folders/files in cache folder will have same permissions.

```py
    # src is a tmp file, dst is the blob path
    cache_dir_mode = Path(dst).parent.stat().st_mode
    os.chmod(src, stat.S_IMODE(cache_dir_mode))
    os.replace(src, dst)
```

The reason behind it that [getting the umask](https://docs.python.org/3/library/os.html#os.umask) from the user is risky. The python implementation consists in changing the value while getting the old value. Can lead to weird/undesired issues in a multi-thread process. I found a [potentially thread-safe solution](https://stackoverflow.com/a/70343066) but didn't want to have to maintain/debug it on multiple platform (solution is more a hack than a proper solution).

cc @stas00 @antoche what do you think ? Looks good to you ? (Also cc @julien-c who worked on the new cache)

### CODE REVIEW

**Comment by stas00** [comment]
I wonder if the simplest way here is to cheat and copy the same perms as some other files other than blob files, since those will be already correctly set as tmpfile isn't used. for example `refs/main` could be the source of truth?

**Comment by Wauplin** [comment]
> in the proposed fix dirmode != filemode - different bits

Aaarrg :sob: :sob: 

> I wonder if the simplest way here is to cheat and copy the same perms as some other files other than blob files, since those will be already correctly set as tmpfile isn't used. for example refs/main could be the source of truth?

We cannot even do that. If the user downloads a file from a specific commit hash, there is no other file created than the blob itself (only folders and a symlink). Especially, there is a `refs/main` file only when users download the latest revision. This is the case 99% of the time but for the 1% remaining, this is a real problem.

```py
# Nothing in `refs/` !
filepath = hf_hub_download(repo_id, "config.json", revision="e9a30121a64df2604d118f7d209411c7202e09c3")
```

--- 

The last solution I see is to create a dumb file with a uuid, check the filemode and delete it. In 99,99% of cases, that would do the trick. Only problem is if the process is shut down while the dumb file still exists (as we cannot do it in a single operation). User would end up with an empty file `.cache/tmp_f32db9df-3b5f-4d63-a01c-706e45d794f1` which is not really problematic right. WDYT @stas00 ?

**Comment by Wauplin** [comment]
@stas00 I made a fix in  https://github.com/huggingface/huggingface_hub/pull/1220/commits/a77aad8782acb8909625d4eb5cc6d8eda560db86 to check current filemode. Can you cross-check what I did is correct ? Thanks in advance :)

**Review by stas00 — APPROVED** [review]
I validated your changes in action and I confirm that the problem has been fixed. Thank you, @Wauplin!

I think your approach of creating a non-`/tmp` temp file to get the target file perms is close to perfection :)

wrt a potential dropped file, at some point we discussed cache purging functionality, why not add a TODO list to clean up any `tmp_*` files in the root of the cache folder whenever that purge is called by the user.

Once merged if possible let's make a new release as this is somewhat a problem with many users each having their own conda env, so it'd be more difficult to ask everybody to work from the bleed edge. Thanky ou!

**Review by LysandreJik — APPROVED** [review]
Sounds like a reasonable change, have you tried/would you like me to try it on windows?

**Comment by Wauplin** [comment]
> have you tried/would you like me to try it on windows?

Thanks for the idea ! I gave it a try and it works as expected :) However the actual test is failing on windows. I still need to figure out how to fix that when setting up a windows CI (but can be done in a future PR)

**Comment by stas00** [comment]
> I'm not against the idea of making a hot-fix release for that if it impacts a lot of users. But I'm not so sure it's the case as the new cache has been release a few months ago and we did not have a lot of requests in that direction.

FWIW, all of HF who works on JeanZay is impacted.

**Comment by Wauplin** [comment]
> FWIW, all of HF who works on JeanZay is impacted.

Hmm, sorry it wasn't raised before then. I can make a hot-release `v0.11.1` on Monday then (don't want to release on a Friday evening :) )

**Comment by stas00** [comment]
Any time soon is no problem, I was just hoping it won't be weeks before the next release.
I asked everybody on JZ to meanwhile run `pip install git+https://github.com/huggingface/huggingface_hub` until then.

**Pull request merged**
