### PR TITLE
Allow append mode in `HfFileSystem._open`

### PR DESCRIPTION
**Pull request by mariosasko**
Needed for https://huggingface.slack.com/archives/C02V5EA0A95/p1680801924044039 (internal Slack thread)

### CODE REVIEW

**Comment by Wauplin** [comment]
Thanks for opening the PR @mariosasko

Unless I'm mistaken, I don't think it's a good idea at the moment to support append mode without a change server-side. Here are the 2 main topics I'm worried about:

**1. Concurrency**

Concurrent calls will lead to data being lost when appending to a file. Does `fsspec` specify anything about concurrency or is it left to the users to ensure they don't append to the same file at the same time?

We might be able to mitigate concurrency calls by using `parent_commit` when uploading a file to ensure no commits have been pushed since the last update. This is not entirely satisfying since the parent_commit is set for the entire repo. In our case it would be best to have something like "file_parent_commit". Still possible to work something out by getting the repo history + using `paths-info` endpoint :confused: 

**2. Optimization**

Idk all the internals about fsspec but I'm afraid that appending data to a file will be highly inefficient. As I understand it right now, the workflow is:
1. The user wants to append a line to a file.
2. We fetch the file from remote.
3. We append a line to the file.
4. We upload the whole file again.
5. Back to 1. to append a new line.

=> In the case of `TensorBoardLogger` where thousands of logs will be written it will lead to a repo with thousands of commits + thousands of downloads/uploads. If it's a LFS file, it means we'll have 1 file duplicated on S3 for each new line added. This is problematic as I don't see how it can be solved client-side anytime soon. I would rather clearly state that we don't support appending data to a file than supporting it with such limitations.

cc @julien-c @Pierrci @coyotte508 It would be really cool if mid-long term we could append bytes to a file on the Hub without the hassle of git commits (cf. the other discussions regarding this). Or at least being able to append bytes without re-uploading the entire file.

**Comment by mariosasko** [comment]
Regarding concurrency, S3 seems to have the same issue based on [this](https://stackoverflow.com/questions/41783903/append-data-to-an-s3-object) SO thread.

But I agree with the second point, so maybe it's best to wait for the "append bytes" API first.

**Comment by julien-c** [comment]
hmm i think that's why i was suggesting to build a custom `TensorBoardLogger` helper (which should only write stuff after batching, or even if possible, just once at the end)

**Comment by julien-c** [comment]
> It would be really cool if mid-long term we could append bytes to a file on the Hub without the hassle of git commits

Yes but this is very very very long term (if ever) 😀

**Comment by Wauplin** [comment]
@mariosasko If that's fine with you, I'd close this PR as "won't fix" for the reason mentioned above.

**Comment by julien-c** [comment]
see also @Wauplin's #1456

**Pull request closed without merging**
