### PR TITLE
Push empty model card and dataset card to the Hub

### PR DESCRIPTION
**Pull request by Wauplin**
Related to https://github.com/huggingface/moon-landing/pull/4815 (private link).

Goal is to keep up-to-date an empty example of ModelCard and DatasetCard, generated by `huggingface_hub`. These examples will be referenced from Hub or from docs.

Cards are pushed to:
- https://huggingface.co/templates/model-card-example
- https://huggingface.co/datasets/templates/dataset-card-example

### CODE REVIEW

**Comment by merveenoyan** [comment]
it's irrelevant but, I was wondering if it would be useful to _eventually_ automatically create these when user pushes model/dataset programmatically through `huggingface_hub` (we already generate for skops inside skops and for Keras in this library)

**Comment by osanseviero** [comment]
As discussed in DM, I find using a token for the `huggingface` org a security risk that we could reduce, as that org has a bunch of important repos. The token could be accidentally leaked if a user does `print(PRODUCTION_TOKEN)` in a test, we don't notice it and run the workflow, we suddenly have an important token exposed. I suggested @Wauplin to use https://huggingface.co/templates instead.

**Comment by Wauplin** [comment]
Thanks for the feedback @osanseviero ! I created a new user [huggingface-hub-ci](https://huggingface.co/huggingface-hub-ci) for which I created a write token. This token is set as environment variable in the github CI. Worse case scenario, someone successfully leaked it and has write access to `huggingface-hub-ci` and [`templates`](https://huggingface.co/templates) organization. Far less critical than previously done :)

Examples are now in https://huggingface.co/templates/model-card-example and https://huggingface.co/datasets/templates/dataset-card-example.

I also changed the script to exit with nice message if the logged in user doesn't have the correct access.

**Comment by julien-c** [comment]
BTW i would once again advocate to remove the table of content from the templates, as the website UI includes a table of content automatically anyways

But i'll open another issue

**Comment by julien-c** [comment]
(cc @meg-huggingface for this ^)

**Comment by Wauplin** [comment]
@julien-c @osanseviero mind approving the PR so that I merge it ? Since you both kinda reviewed already :)

**Review by julien-c — APPROVED** [review]
tiny nit, would you mind removing the table of contents from the templates too (on the fly)?

**Comment by Wauplin** [comment]
> tiny nit, would you mind removing the table of contents from the templates too (on the fly)?

Did it. It will be a good occasion to check CI works fine to push updated versions :)

**Pull request merged**
