### PR TITLE
Add input validation for structured-data-classification

### PR DESCRIPTION
**Pull request by osanseviero**
Required for #90

### CODE REVIEW

**Comment by osanseviero** [comment]
Hi @Narsil, this is ready for review based on #98 discussion.

**Review by Narsil — COMMENTED** [review]
Seems good,

However, isn't the query for `structured` data not there for `structured-data-classification`? 

The query **is** the table no ?

**Comment by osanseviero** [comment]
Whoops, tried to reuse too much.

I updated the validation and tests

**Review by Narsil — APPROVED** [review]
LGTM

**Pull request merged**
