### PR TITLE
Fix Error messages

### PR DESCRIPTION
**Pull request by philschmid**
This PR fixes the validator for top_p, which should be allows to be set to 1.0.

### CODE REVIEW

**Review by Wauplin — COMMENTED** [review]
Conceptual approval but please wait for @OlivierDehaene confirmation before merging (I took this validation rule from the former TGI client).

@philschmid looks like a test has to be updated in `../tests/test_inference_text_generation.py` after the condition update.

**Comment by OlivierDehaene** [comment]
1.0 is not a valid value. `top_p` must be > 0.0 and < 1.0.

**Comment by philschmid** [comment]
> 1.0 is not a valid value. `top_p` must be > 0.0 and < 1.0.

doesn't transformers support 1.0?

**Comment by Wauplin** [comment]
Since https://github.com/huggingface/huggingface_hub/pull/2094 there is no client-side validation (no pydantic) to avoid this kind of situation where we can't know before-hand which values the server is able to handle. I'm therefore closing this PR without merging.

**Pull request closed without merging**
