### PR TITLE
Respect `.gitignore` file in commits

### PR DESCRIPTION
**Pull request by Wauplin**
Solves #1826 and follow-up after server-side change (https://github.com/huggingface/moon-landing/pull/8007 - private link).

I have now added a `respect_gitignore: bool = True` parameter to `create_commit` and `upload_folder` to respect the gitignore file, if it exists.

By default we check if a .gitignore file is present in the commit itself. Otherwise the one hosted on the Hub is used. Only the gitignore file at root is respected (not in subdirectories).

I have adapted the documentation and added a few tests for it.

**Note:** as mentioned by @julien-c in https://github.com/huggingface/huggingface_hub/issues/1826#issuecomment-1810934088, let's consider this as a "bug-fix" and not a "breaking change" as we can expect that no-one was intentionally uploading ignored files on purpose. 

---

```sh
# Test to upload my `huggingface_hub/` folder to the Hub
>>> huggingface-cli upload test_tmp_upload ../huggingface_hub
Skipped upload for 53 LFS file(s) (ignored by gitignore file).
Skipped 597 file(s) in commit (ignored by gitignore file).
https://huggingface.co/Wauplin/test_tmp_upload/tree/main/.
```

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Yes! And I agree that this is a bugfix.

The implementation looks good to me.

**Comment by Wauplin** [comment]
Thanks for the review @LysandreJik! Failing tests are unrelated so I'll merge this one and fix the CI in a separate PR.

**Comment by julien-c** [comment]
sorry i'm late to this, but are you sure we even needed a `respect_gitignore` param? Feels unlikely that anyone will ever want to set it to False no?

**Comment by Wauplin** [comment]
Opened a PR to remove `respect_gitignore` before it's too late :smile: https://github.com/huggingface/huggingface_hub/pull/1876

**Pull request merged**
