### PR TITLE
Update some widgets to use `textarea` rather than `input`

### PR DESCRIPTION
**Pull request by mishig25**
1. Updated widgets (FillMaskWidget (which is TextClsWidget), TokenClsWidget, TextToSpeechWidget) to use `textarea` as their input element, rather than `input`. 
2. Made `textarea` input height auto-growable until 500px

[Checkout netlfy demo here](https://6193b4a5ec227207e6ff4874--huggingface-widgets.netlify.app/)

cc: @Pierrci @lewtun 

Closes https://github.com/huggingface/moon-landing/issues/1523

<video src="https://user-images.githubusercontent.com/11827707/141996190-8c8f551f-f4d0-48b6-b451-071ea81737f7.mov" controls autoplay loop/>

### CODE REVIEW

**Comment by lewtun** [comment]
Wow that was quick, thanks @mishig25 for this great quality-of-life improvement!

**Comment by mishig25** [comment]
@lewtun please let me know if you have any other suggestions on the widgets 👍

**Review by gary149 — COMMENTED** [review]
Nice improvement! I found a little issue when you copy/paste (only on firefox). I don't think it's really a problem though. (it does it when copying from a contenteditable input). WDYT?

https://user-images.githubusercontent.com/3841370/142167470-d5668ecf-3f1f-4865-b957-2a8c24ca1d18.mov

**Comment by mishig25** [comment]
@gary149 added the fix for the bug, feel free to re-review 👍

**Review by gary149 — APPROVED** [review]

**Pull request merged**
