### PR TITLE
Fix Audio Classification pipeline

### PR DESCRIPTION
**Pull request by osanseviero**
Sort audio classification results by probability, not by label....

### CODE REVIEW

**Comment by julien-c** [comment]
(just noting that I'm not sure this is consistent with `text-classification` where IIRC we keep the label list's order)

**Comment by osanseviero** [comment]
@anton-l what do we do for `audio-classification` in `transformers`? Do we keep top_k and then sort by probability? Or do we keep top_k and then keep label list's order.

**Comment by anton-l** [comment]
@osanseviero in the end the labels are ordered by probability (decreasing), regardless of top_k

**Comment by julien-c** [comment]
(ah yeah if you do topk then it doesn't make a lot of sense to order by label list. For `text-classification` I think we keep label order because we don't do topk – I might be wrong)

**Comment by osanseviero** [comment]
Yeah we do `top_k`, specially for speaker verification or language id there can be hundreds or thousands of labels

**Comment by Narsil** [comment]
> (just noting that I'm not sure this is consistent with text-classification where IIRC we keep the label list's order)

@julien-c for transformers, by default the pipeline uses `~top_k=1` and returns only 1 result. For the API, there's an override with `return_all_scores=True` which will return all scores (no sorting). And it does not have a `top_k` argument.

It's definitely something that can be improved, especially to confirm with `image-classification` and `audio-classification`. Only issue is backward compatibility in transformers.

**Pull request merged**
