### PR TITLE
Update Hub and huggingface_hub docs

### PR DESCRIPTION
**Pull request by osanseviero**
This PR does two things
* Updates the add a model guide based on feedback
* Does a general cleanup/update/simplification of `huggingface_hub` README.

### CODE REVIEW

**Review by julien-c — APPROVED** [review]
good improvements

(nit) Not a fan of the 80-char line wrapping as it makes subsequent diffs hard to read

**Comment by LysandreJik** [comment]
Was actually thinking of bumping up the `black` character limit to 119 like `transformers`, it greatly improves readability imo

**Comment by julien-c** [comment]
hmm those are .md files

**Review by LysandreJik — APPROVED** [review]
Looks good to me, thanks for completing the docs with the docstrings!

**Comment by LysandreJik** [comment]
> hmm those are .md files

Yes, I was talking about the Python files, not the files here. Bouncing back on your comment that 80 characters isn't necessarily more readable!

**Pull request merged**
