### PR TITLE
Create commit by streaming a ndjson payload (allow lots of file in single commit)

### PR DESCRIPTION
**Pull request by Wauplin**
Will fix https://github.com/huggingface/huggingface_hub/issues/1085. Related to https://github.com/nateraw/huggingface-datasets-converter/issues/20, https://github.com/nateraw/huggingface-datasets-converter/issues/13.

Work was started in https://github.com/huggingface/huggingface_hub/pull/920 (by @SBrandeis) and I completed it to use the new `ndjson` format to upload a large amount of files at once (25k LFS files / 1GB payload max for the `/create_commit` endpoint). Thanks @coyotte508 for the moon-landing implementation :pray: 

**Main changes:**
1. Retrieving preupload info (is it regular of LFS file ?) is now done by chunks of 128 files. Fails on first failure (remaining chunks are not tested).
2. Retrieving upload info for LFS files is now done by chunks of 128 files. Fails on first failure.
3. LFS files are uploaded 1 by 1 (5 threads in parallel) => nothing changed, same as before
4. Finally `/create_commit` endpoint is called using the `"application/x-ndjson"` content type [as described by @coyotte508](https://github.com/huggingface/huggingface_hub/issues/1085#issuecomment-1265208073).

I also fixed the implementation of `http_backoff` that was currently broken when uploading files.

I am not exactly sure how to test all of this. The implemented test is to upload 600 files and see if it fails or not but I'm a bit worried that is very long and not so reliable (hopefully not with the http_backoff, but can still fail randomly). **EDIT: it takes ~7min in the CI...** @LysandreJik any ideas on how to improve that ? I see 2 solutions here: either do unit tests using mocks everywhere (cons: would not test "in real usage"), either do end2end tests as now but in a separate CI build (cons: at least 2 additional CI build - 1 per python version). 

(cc @julien-c @Pierrci @SBrandeis @coyotte508 from the moon-landing team)
(also cc @osanseviero @nateraw @merveenoyan who already experienced limitations with the create_commit endpoint. **Note**: `upload_folder` will also benefit from this change as it wraps the `create_commit` method)

### CODE REVIEW

**Review by coyotte508 — APPROVED** [review]
Very well documented PR :)

**Comment by LysandreJik** [comment]
Do we need to upload as much as 600 files? I'd much rather not mock it here to have at least one real test, but 600 files seems like a large number.

**Comment by Wauplin** [comment]
> Do we need to upload as much as 600 files? 

Actually I just made some local tests and it turns out that 600 regular + 600 LFS was already working fine on `main` branch. I need to increase to 700 to get a request entity too large. So if we really want to test the new feature end-to-end, we need to upload all those files :confused: 

I agree with you on the mocks not being satisfying. I mentioned it because it's a possibility but we wouldn't really be testing the limits of the API.

**Comment by coyotte508** [comment]
JFI you can upload 10 files of 9MB each with base64 encoding, (or 12 with utf-8) and it would reach beyond the old limits

**Comment by Wauplin** [comment]
> JFI you can upload 10 text files of 9MB each with base64 encoding, (or 12 with utf-8) and it would reach beyond the old limits

@coyotte508 good to know thanks ! I'll try that :)

**Comment by Wauplin** [comment]
@coyotte508 @LysandreJik I have adapted the tests.

- I now have `test_create_commit_huge_regular_files` that tries to commit 12 files of 9MB each at once. Do not work on `main` but now yes thanks to the `ndjson` format.
- And a `test_commit_preflight_on_lots_of_lfs_files` that tries to fetch upload mode for 1300 files (`fetch_upload_modes`). Test is passing thanks to the chunking. 

Both tests are "quite reasonable" in term of time (~5s) so I think we can keep them like this and we avoid the full end-to-end test with >1000 files to upload. Thanks both for your inputs ! :slightly_smiling_face:

**Comment by Wauplin** [comment]
@LysandreJik just wanted to cross-check if this PR is fine for you (e.g. I can merge ?) given the latest changes in the tests. Same @coyotte508 as you approved but then I made a few changes.
If you both agree, I merge it and we are finally good to upload thousands of files :smiling_imp:

**Comment by coyotte508** [comment]
It's fine for me :) (but I'm not a python maintainer so someone else should definitely approve as well)

**Review by LysandreJik — APPROVED** [review]
Yeah this looks good to me, thanks @Wauplin!

**Comment by Wauplin** [comment]
Cool, thanks for the reviews :hugs:

**Pull request merged**
