### PR TITLE
Implemented CLI download functionality

### PR DESCRIPTION
**Pull request by martinbrose**
Addresses #1105.

- #1105

### CODE REVIEW

**Review by Wauplin — APPROVED** [review]
Hi @martinbrose, thanks a ton for working on this PR! It is a quite expected feature that will drastically simplify how some users are downloading weights from the Hub. The goal is to kinda replace `git clone`-like commands by this one :rocket: :hugs: 

I started to try the CLI locally and got opinionated on how the command should look like which lead to me making changes directly on your PR. I hope you didn't find it offensive :) Here is how the command looks like now:

```sh
# Download file
huggingface-cli download gpt2 config.json

# Download entire repo
huggingface-cli download fffiloni/zeroscope --repo-type=space --revision=refs/pr/78

# Download repo with filters
huggingface-cli download gpt2 --include="*.safetensors"

# Download with token
huggingface-cli download Wauplin/private-model --token=hf_***

# Download quietly (no progress bar, no warnings, only the returned path)
huggingface-cli download gpt2 config.json --quiet
```

**Comment by martinbrose** [comment]
Thanks @Wauplin,

I've reviewed your changes with interest and they made sense to me.
Of course, feel free to change how you see fit.

Cheers

**Review by Wauplin — APPROVED** [review]
@LysandreJik @julien-c Would you mind having a look to this PR as it adds a quite important command IMO (also cc @osanseviero). Might be interesting to showcase this command in the "Clone this model repository" pop-up on the Hub. Before doing so, we would need the `--to-local-dir` option to be implemented but that can be done in a future PR.

cc @stevhliu I have added [a small section in the docs](https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_1617/en/guides/download#download-from-the-cli) if you can have a look at it :pray: 


**EDIT:** implemented `--to-local-dir` in https://github.com/huggingface/huggingface_hub/pull/1617/commits/874b70e0d7720af458d95a90cb0908d3ba7c882b

**Comment by Wauplin** [comment]
> Do you think we could have a shorter command (huggingface-cli is long). Maybe hf-cli, or hf?

I'm definitely in favor of a simple `hf` ! Often thought about it but never made the change. We would still keep both `hf` and `huggingface-cli` for backward compatibility. We can do it in a future PR (also I don't know how much @julien-c or @LysandreJik are opinionated on the subject :smile: )

**Comment by julien-c** [comment]
re shorter command name, i wouldn't recommend because:
- users have auto-complete in their shells?
- let's not fragment usage as huggingface-cli already exists and is widely documented
- there's even system packages (brew etc) with that name

**Review by julien-c — COMMENTED** [review]
API-wise, looks great to me!

and i liked the detailed pre-spec in https://github.com/huggingface/huggingface_hub/issues/1105#issuecomment-1623470449 cc @Wauplin 

I think this will be quite a useful feature!

**Review by LysandreJik — APPROVED** [review]
Played with it, works well! I like the API. Thanks for working on it @Wauplin

**Pull request merged**
