### PR TITLE
Refresh Spaces docs

### PR DESCRIPTION
**Pull request by stevhliu**
As discussed in #443, this PR reorganizes the Spaces docs from a question-answer format to something with more structure and narrative. Some things to note:

- The link to the RAG app is broken. Do we want to include a link to the Facebook (or Meta? 🥸) [RAG blog post](https://ai.facebook.com/blog/retrieval-augmented-generation-streamlining-the-creation-of-intelligent-natural-language-processing-models/) instead?
- Still need to find a home for the Changelog. Maybe we can include them as [release](https://github.com/huggingface/datasets/releases) notes as Datasets does?

### CODE REVIEW

**Comment by julien-c** [comment]
can you please tag @cbensimon the lead engineer for Spaces?

Personally I'm not a huge fan of this rewrite (and i think we still need the changelog – this is not a library so GitHub release notes are not really an option)

**Comment by stevhliu** [comment]
Thanks for the feedback! :) Is there some aspect of the rewrite you aren't a fan of?

Maybe we can create a new Changelog section on the side for the Hub as a whole? 🤔  This way we can also document changes to other aspects of the Hub.

**Comment by julien-c** [comment]
> Is there some aspect of the rewrite you aren't a fan of?

a bit swamped right now but I'll give it a go soon

I would just keep the changelog where it is for now

**Comment by julien-c** [comment]
rebased on master + tweaks

**Review by julien-c — APPROVED** [review]

**Comment by stevhliu** [comment]
LGTM, merging now :)

**Pull request merged**
