### PR TITLE
Fix URL in `get_safetensors_metadata` docstring

### PR DESCRIPTION
**Pull request by Wauplin**
~Tweak safetensors parser: fetch only 25kb by default (instead of 100kb currently). Still valid for most use cases (82% in top 1000 models) and save some bandwidth. Most probably won't be noticed. (see https://github.com/huggingface/huggingface_hub/pull/1855#discussion_r1404286419)~ => EDIT: not changed in the end.

Fix typo in docs: wrong url in `get_safetensors_metadata` docstring.

### CODE REVIEW

**Comment by LysandreJik** [comment]
Did we encounter a problem with 100kb? I think it's reasonable enough already so wondering if we need the change

**Comment by Wauplin** [comment]
> Did we encounter a problem with 100kb? I think it's reasonable enough already so wondering if we need the change

No problems reported no.
It's just that I thought saving 4x bandwidth in 82% percent of cases while adding an extra HEAD call in 15% of cases seemed reasonable. But fine with keeping 100kb if you feel like it

**Comment by julien-c** [comment]
i would also tend to not change anything, personally..

**Comment by Wauplin** [comment]
Ok, reverted in https://github.com/huggingface/huggingface_hub/pull/1951/commits/456555ac271d0828aa0572c3195cfb3c8d61c8a1.

PR becomes "fix typo in docs" :)

**Pull request merged**
