### PR TITLE
Updating MC headings

### PR DESCRIPTION
**Pull request by EziOzoani**
Updating the Markdown headings so it tracks with the HTML
(see [this thread](https://huggingface.slack.com/archives/C025H22A3ND/p1677198938931089?thread_ts=1677181385.790839&cid=C025H22A3ND))

Fixes: https://github.com/huggingface/huggingface_hub/issues/1366

### CODE REVIEW

**Review by Wauplin — COMMENTED** [review]
Suggestion makes total sense! 
Looks good to me. Could you update the Dataset Card template as well? :pray: => https://github.com/huggingface/huggingface_hub/blob/ezi/src/huggingface_hub/templates/datasetcard_template.md

**Comment by EziOzoani** [comment]
@Wauplin for _**this**_ update I think the dataset card is already okay, there is only one singular `#` i.e h1 iirc in html

**Review by Wauplin — APPROVED** [review]
> for this update I think the dataset card is already okay, there is only one singular # i.e h1 iirc in html

Oops sorry for that, I have been too quick in my review then. It's approved! :)

**Comment by EziOzoani** [comment]
No problemo
thanks for the merge @Wauplin , super appreciate d💃💃

**Comment by NimaBoscarino** [comment]
Yay this is fantastic! Thanks for doing this!!

**Pull request merged**
