### PR TITLE
Update model-repos.md

### PR DESCRIPTION
**Pull request by sashavor**
Making yaml changes as per @julien-c 's guidelines :green_heart: 

cc @osanseviero @LysandreJik

### CODE REVIEW

**Comment by sashavor** [comment]
Sorry I missed your initial comment @julien-c  (I thought I had saved the file but I must have not done so) -- fixing now!

**Comment by julien-c** [comment]
thanks! ✨

**Review by osanseviero — APPROVED** [review]
Looks good! Thanks for the fix

**Review by LysandreJik — APPROVED** [review]
Looks great, thanks @sashavor!

**Pull request merged**
