### PR TITLE
Handle `refs/convert/parquet` and PR revision correctly in hffs

### PR DESCRIPTION
**Pull request by Wauplin**
Solves https://github.com/huggingface/huggingface_hub/issues/1710 by processing `refs/convert/parquet` and `refs/pr/(\d)+` as special revisions when resolving a path. Also make sure that the `unresolve` counterpart works the same. Also added some tests for it.

Use case from @Hakimovich99 now works properly without having to url-encode the revision. This time I tested with [jamescalam/llama-2-arxiv-papers-chunked](https://huggingface.co/datasets/jamescalam/llama-2-arxiv-papers-chunked) dataset which doesn't have parquet files on `main` revision:

```py
>>> from dask import dataframe as dd
>>> dd.read_parquet("hf://datasets/jamescalam/llama-2-arxiv-papers-chunked@refs/convert/parquet")
# Dask DataFrame Structure:
#                  doi chunk-id   chunk      id   title summary  source authors categories comment journal_ref primary_category published updated references
# npartitions=1                                                                                                                                              
#               object   object  object  object  object  object  object  object     object  object      object           object    object  object     object
#                  ...      ...     ...     ...     ...     ...     ...     ...        ...     ...         ...              ...       ...     ...        ...
# Dask Name: read-parquet, 1 graph layer

>>> dd.read_parquet("hf://datasets/jamescalam/llama-2-arxiv-papers-chunked@refs/convert/parquet/default/train/0000.parquet")
# Dask DataFrame Structure:
#                   doi chunk-id   chunk      id   title summary  source authors categories comment journal_ref primary_category published updated references
# npartitions=1                                                                                                                                              
#                object   object  object  object  object  object  object  object     object  object      object           object    object  object     object
#                   ...      ...     ...     ...     ...     ...     ...     ...        ...     ...         ...              ...       ...     ...        ...
# Dask Name: read-parquet, 1 graph layer
```

This should be a small QOL improvements for datasets users while not degrading the experience for others.

### CODE REVIEW

**Comment by lhoestq** [comment]
Btw forgot to mention this in the other issue but using the `~parquet` alias works:


 ```python
dd.read_parquet("hf://datasets/jamescalam/llama-2-arxiv-papers-chunked@~parquet")
```

**Comment by Wauplin** [comment]
> Btw forgot to mention this in the other issue but using the ~parquet alias works:

Aaaah, right. Completely forgot as well. I think that's why I thought we already talked about simplifying the revision (as mentioned in https://github.com/huggingface/huggingface_hub/issues/1707#issuecomment-1746431572). Anyway, I think handling parquets + PR refs differently is also good in addition to of the `~parquet` alias.

**Review by lhoestq — APPROVED** [review]
Looks good to me !

**Comment by Wauplin** [comment]
Thanks for the review! Failing tests are unrelated so I'll merge now :)

**Pull request merged**
