### PR TITLE
Add object detection to inference client

### PR DESCRIPTION
**Pull request by dulayjm**
**Add object-detection to HuggingFace🤗 Hub**  

References [Issue #1539](https://github.com/huggingface/huggingface_hub/issues/1539)

This is an ongoing list of model tasks to implement in the Hugging Face Hub inference client. Each task is planned to be its own PR. The task for this is [object-detection](https://huggingface.co/tasks/object-detection).

** Key Features ** 
* Modifies `_client.py` to call an object detection model. The example model is [DETR ResNet-50](https://huggingface.co/facebook/detr-resnet-50). 
* Modifies testing and documentation to reflect changes.

### CODE REVIEW

**Review by Wauplin — APPROVED** [review]
Very clean implementation! Thanks for working on it @dulayjm !

I tested it locally and re-recorded the test (there were 3 requests made, making the file quite huge). Worked like a charm for me at first use :D If everything's fine in the CI, it is ready to be merged straight away :hugs:

**Comment by dulayjm** [comment]
@Wauplin Thanks! 

The code seems to still fail the CI, but I have a question about that. On the `Python Quality` check, it fails with some messages at the end. In particular, the `LocalTokenNotFoundError` is one I'm seeing a couple of times. Is there something that needs to be different about the VCR testing?

```
=========================== short test summary info ============================
FAILED ../tests/test_commit_scheduler.py::TestCommitScheduler::test_mocked_push_to_hub - AssertionError: 2 not greater than 2
FAILED ../tests/test_hf_api.py::HfApiListFilesInfoTest::test_list_files_with_expand - AssertionError: False is not true
FAILED ../tests/test_webhooks_server.py::TestWebhooksServerRun::test_run_parse_payload - AssertionError: 422 != 200
ERROR ../tests/test_hf_api.py::TestSpaceAPIProduction::test_manage_secrets - huggingface_hub.utils._headers.LocalTokenNotFoundError: Token is required (`token=True`), but no token found. You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`. See https://huggingface.co/settings/tokens.
ERROR ../tests/test_hf_api.py::TestSpaceAPIProduction::test_pause_and_restart_space - huggingface_hub.utils._headers.LocalTokenNotFoundError: Token is required (`token=True`), but no token found. You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`. See https://huggingface.co/settings/tokens.
ERROR ../tests/test_hf_api.py::TestSpaceAPIProduction::test_space_runtime - huggingface_hub.utils._headers.LocalTokenNotFoundError: Token is required (`token=True`), but no token found. You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`. See https://huggingface.co/settings/tokens.
= 3 failed, 660 passed, 40 skipped, 60 deselected, 120 warnings, 3 errors in 342.14s (0:05:42) =
Error: Process completed with exit code 1.
```

**Comment by dulayjm** [comment]
Awesome, thank you so much!

**Comment by julien-c** [comment]
This is really cool! Random unsollicited question, did you try out the huggingface.js implementation? https://huggingface.co/docs/huggingface.js/inference/classes/HfInference#objectdetection

(same client, but in JS)

**Comment by dulayjm** [comment]
Thank you!!

 No, I haven't checked out the JS library, but I'll give it a look! 🤗

**Pull request merged**
