### PR TITLE
Add --exclude-standard argument in git ls-files command

### PR DESCRIPTION
**Pull request by DougTrajano**
This pull request introduces the `--exclude-standard` argument to the git ls-files command.

As described in [Git - git-ls-files Documentation](https://git-scm.com/docs/git-ls-files#_options), this option adds the standard Git exclusions: .git/info/exclude, .gitignore in each directory, and the user’s global exclusion file.

This change is important because the current behavior of the command can return temporary files that may be deleted during the execution, leading to a race condition. With the new option, files that match the exclusion patterns in the .gitignore file will not be returned.

Further details can be found at the https://github.com/huggingface/transformers/issues/21586

### CODE REVIEW

**Review by Wauplin — APPROVED** [review]
Hi @DougTrajano, thank you for the PR and the detailed analysis done in https://github.com/huggingface/transformers/issues/21586. It seems really legit to use this `--exclude-standard` argument. To be very honest I didn't know that the `.gitignore` is not taken into account by default.

@LysandreJik @sgugger Can I have a second approval on this PR please? Just want to confirm the approach is good for you as well.

**Review by julien-c — COMMENTED** [review]
i guess we don't need to add a flag to disable this addition (and keep the current behavior)?

(i don't think we do)

**Comment by Wauplin** [comment]
> i guess we don't need to add a flag to disable this addition (and keep the current behavior)?

True that it adds a "breaking change". I thought the same but really I don't see a use case where a user wants to track an LFS files even though it's in the `.gitignore`.

**Comment by julien-c** [comment]
yep agreed!

and thanks a lot @DougTrajano for the solid contribution  ❤️

**Pull request merged**
