### PR TITLE
[WIP] enable pytest-xdist in CI

### PR DESCRIPTION
**Pull request by Wauplin**
Related to https://github.com/huggingface/huggingface_hub/issues/970.

Draft mode since it's not close to be reviewed :D

### CODE REVIEW

**Comment by bmuskalla** [comment]
@Wauplin Is this still something you plan on doing? Looking at the changes (and the PR creation date), it seems like most of the issues have been resolved by leveraging `SoftTemporaryDirectory`. Running the non-repo tests with `pytest-xdist` also seems to be working fine locally (ignore the two errors, those are still setup issues and not related to `pytest-xdist`
```
python -m pytest ./tests -n auto -k 'not TestRepository'
==== 2 failed, 904 passed, 37 skipped, 47 warnings in 150.30s (0:02:30) ====
```

The only thing left to do would be to adapt the workflow action. Or do you see other things that should be considered for this?

**Comment by Wauplin** [comment]
Hey @bmuskalla thanks for opening up this topic!

I actually opened this draft PR just the week after I started at HF and soon realized it would be quite difficult to achieve in one PR. But as you mentioned, now that the cache dir fixed most of the dependencies between tests, it looks like it all working great! :fire: :fire: :fire: 

Would you like to open a new PR to update the workflow action and see how it goes? I suspect there might be issues on the Windows CI to perform all tests concurrently (at least that was the case when I added this CI in https://github.com/huggingface/huggingface_hub/pull/1112) but maybe it's more manageable now :) Let's try and see. If you do so, I'll close this PR which is too outdated anyway.

(FYI, at some point there was also the question of how much load the staging environment was able to handle concurrently but that's not much of a topic anymore :) ).

**Comment by Wauplin** [comment]
BTW, following your comment I've looked at the CI a bit and realized we could make 2 of the tests much faster. I fixed it in https://github.com/huggingface/huggingface_hub/pull/2054 (~1min gain).

**Comment by bmuskalla** [comment]
Thanks for all the context @Wauplin , let's see how far we get with enabling this across the various test sets: #2059 

> BTW, following your comment I've looked at the CI a bit and realized we could make 2 of the tests much faster. 

Dang, I already had a local change for the "let's fetch all spaces on hf.co" test ;) Good to see those being improved

**Pull request closed without merging**
