### PR TITLE
Pass revision in path to AbstractBufferedFile init

### LINKED ISSUE #1947: Parameter revision is not taken into account by HfFileSystem
### Describe the bug

I created and then deleted a file from the repo. When I try to open the removed file, by passing the corresponding `revision`, I get `FileNotFoundError`.

See example below, which uses the repo: https://huggingface.co/datasets/albertvillanova/ai2_arc/commits/main

### Reproduction

```python
from huggingface_hub import HfFileSystem
fs = HfFileSystem()
with fs.open("datasets/albertvillanova/ai2_arc/ai2_arc.py", "r", encoding="utf-8", revision="f5cdce6f1179d2c391582eb32af16a742ae744d5") as f:
    data = f.read()
```

### Logs

```shell
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-6cd92de402ba> in <cell line: 1>()
----> 1 with fs.open("datasets/albertvillanova/ai2_arc/ai2_arc.py", "r", encoding="utf-8", revision="f5cdce6f1179d2c391582eb32af16a742ae744d5") as f:
      2     data = f.read()

7 frames
/usr/local/lib/python3.10/dist-packages/fsspec/spec.py in open(self, path, mode, block_size, cache_options, compression, **kwargs)
   1227             }
   1228             return io.TextIOWrapper(
-> 1229                 self.open(
   1230                     path,
   1231                     mode,

/usr/local/lib/python3.10/dist-packages/fsspec/spec.py in open(self, path, mode, block_size, cache_options, compression, **kwargs)
   1239         else:
   1240             ac = kwargs.pop("autocommit", not self._intrans)
-> 1241             f = self._open(
   1242                 path,
   1243                 mode=mode,

/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_file_system.py in _open(self, path, mode, revision, **kwargs)
    221         if "a" in mode:
    222             raise NotImplementedError("Appending to remote files is not yet supported.")
--> 223         return HfFileSystemFile(self, path, mode=mode, revision=revision, **kwargs)
    224 
    225     def _rm(self, path: str, revision: Optional[str] = None, **kwargs) -> None:

/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_file_system.py in __init__(self, fs, path, revision, **kwargs)
    594 class HfFileSystemFile(fsspec.spec.AbstractBufferedFile):
    595     def __init__(self, fs: HfFileSystem, path: str, revision: Optional[str] = None, **kwargs):
--> 596         super().__init__(fs, path, **kwargs)
    597         self.fs: HfFileSystem
    598 

/usr/local/lib/python3.10/dist-packages/fsspec/spec.py in __init__(self, fs, path, mode, block_size, autocommit, cache_type, cache_options, size, **kwargs)
   1595                 self.size = size
   1596             else:
-> 1597                 self.size = self.details["size"]
   1598             self.cache = caches[cache_type](
   1599                 self.blocksize, self._fetch_range, self.size, **cache_options

/usr/local/lib/python3.10/dist-packages/fsspec/spec.py in details(self)
   1608     def details(self):
   1609         if self._details is None:
-> 1610             self._details = self.fs.info(self.path)
   1611         return self._details
   1612 

/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_file_system.py in info(self, path, refresh, revision, **kwargs)
    519                 )
    520                 if not paths_info:
--> 521                     _raise_file_not_found(path, None)
    522                 path_info = paths_info[0]
    523                 root_path = HfFileSystemResolvedPath(

/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_file_system.py in _raise_file_not_found(path, err)
    668     elif isinstance(err, HFValidationError):
    669         msg = f"{path} (invalid repository id)"
--> 670     raise FileNotFoundError(msg) from err

FileNotFoundError: datasets/albertvillanova/ai2_arc/ai2_arc.py
```

### System info

```shell
- huggingface_hub version: 0.20.1
- Platform: Linux-6.1.58+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Running in iPython ?: Yes
- iPython shell: Shell
- Running in notebook ?: Yes
- Running in Google Colab ?: Yes
- Token path ?: /root/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: 2.7.13
- Tensorflow: 2.15.0
- Torch: 2.1.0+cu121
- Jinja2: 3.1.2
- Graphviz: 0.20.1
- Pydot: 1.4.2
- Pillow: 9.4.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.23.5
- pydantic: 1.10.13
- aiohttp: 3.9.1
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /root/.cache/huggingface/hub
- HF_ASSETS_CACHE: /root/.cache/huggingface/assets
- HF_TOKEN_PATH: /root/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

### PR DESCRIPTION
**Pull request by albertvillanova**
Fix #1947.

### CODE REVIEW

**Review by Wauplin — COMMENTED** [review]
Thanks for opening a PR to fix the issue @albertvillanova! I'm not sure though to understand what could be the side effects of initializing with `path` instead of `resolved_path.unresolve()` (@mariosasko could you double-check as well).

Since it's fixing an issue, @albertvillanova could you add a regression test in [test_hf_file_system.py](https://github.com/huggingface/huggingface_hub/blob/main/tests/test_hf_file_system.py)? Thanks in advance!

**Comment by albertvillanova** [comment]
@Wauplin, as requested, I have added a regression test.

**Review by Wauplin — APPROVED** [review]
Thanks for adding the test @albertvillanova! 

I also tried it myself and looks good. Let's wait for a quick review from @mariosasko or @lhoestq before merging (if it's not a hurry on your side). Thanks for the fix!

**Review by lhoestq — APPROVED** [review]
Thanks for the fix !

**Comment by Wauplin** [comment]
Thanks for the review, will merge it now :)

**Pull request merged**
