### PR TITLE
docs: fix webhook response format

### PR DESCRIPTION
**Pull request by severo**

### CODE REVIEW

**Comment by julien-c** [comment]
arg this was actually intended, I'm deprecating the previous array-contained format (as the array always one 1 element anyways)

**Comment by julien-c** [comment]
mind reverting?

**Comment by severo** [comment]
hmmm, no problem for me, but... my poor https://github.com/huggingface/tensorboard-launcher will break again if you change the API response. When do you think switching to the new format?

**Comment by julien-c** [comment]
this is already deployed, but I preserved backward compatibility for you + other current subscribers.

see [this commit](https://github.com/huggingface/moon-landing/pull/871)

**Pull request merged**
