### PR TITLE
Add generic return type to `from_pretrained`

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

## Pull Request overview
* Add generic return type to `from_pretrained`, allowing for all subclasses of `ModelHubMixin` to get typed correctly when loading a model using `from_pretrained`.
* Add tests to ensure that the generic return type is not removed.

## The issue
Let's first discuss the issue that this PR tries to fix, as I realise that the PR overview and title are vague. Let's consider the following snippet:
```python
from huggingface_hub.hub_mixin import PyTorchModelHubMixin, ModelHubMixin

class DummyTorchModel(PyTorchModelHubMixin):
    pass

class DummyModel(ModelHubMixin):
    def my_special_method(self, x: int = 12) -> int:
        return x ** 3

torch_model = DummyTorchModel.from_pretrained("namespace/repo_name")
model = DummyModel.from_pretrained("namespace/repo_name")

model.my_special_method(4)
```
Modern IDE's are able to recognize the type information of `torch_model` and `model` using the signature from `from_pretrained`. However, [the `from_pretrained` signature doesn't specify a return type](https://github.com/huggingface/huggingface_hub/blob/a4b1b33cea6ed825439b536cd384083816316a2e/src/huggingface_hub/hub_mixin.py#L102). As a result, `torch_model` and `model` are typed as `typing.Any`. This prevents autocompletions and hinting of methods of `ModelHubMixin` its subclasses such as `DummyTorchModel` and `DummyModel`, and is generally extremely undesirable:
image
image
image

## The solution
This can easily be resolved by using a generic [TypeVar](https://docs.python.org/3/library/typing.html#typing.TypeVar). Consider the following snippet:
```python
T = TypeVar("T", bound="MyClass")

class MyClass:
    @classmethod
    def my_method(
        cls: Type[T],
        ...
    ) -> T:
```
The Python type hinting solution will evaluate T using the value given to `cls`, which allows the type hinter to recognize that the output of the method is the same as the class on which it was called. Note that `bound="MyClass"` limits what `T` can be evaluated as to only `MyClass` and subclasses of `MyClass`.

## The effect
If we revisit the same snippet at the issue section from before, but now on this PR's branch, we get these screenshots:
image
image
image

Perfect!
When this is merged, I can stop doing this:
```python
model: SetFitModel = SetFitModel.from_pretrained(...)
```

Let me know if you need anything from me at this point!

- Tom Aarsen

### CODE REVIEW

**Comment by tomaarsen** [comment]
Hey! I'm just noticing b1fd1a430b30b7a92f483485a13bfa48c244fcf4 which does away with `isort` etc. Shall I merge `main` into this to potentially resolve some of the CI failures? That said, they won't help with the `test_hf_api.py::TestSpaceAPIProduction` test failures. 
Let me know how best I can help (including just letting you handle it, I'm well aware that can be easier for the both of us :) )

- Tom Aarsen

**Comment by Wauplin** [comment]
Hi @tomaarsen, thanks a lot for your PR! Explanations are clear, I totally get your point here. 
3 things:
- Could you also add a return type to [`from_pretrained_keras`](https://github.com/huggingface/huggingface_hub/blob/96b6279fece34f1aa10f5fb82a64b2b6a930c979/src/huggingface_hub/keras_mixin.py#L219) please? It's not exactly related to what you did but would be good to fix both at the same time. Output type should be `KerasModelHubMixin`. It was not possible before (mypy would complain) but now with your fix it should be ok.
- Indeed we changed our formatting rules very recently. Sorry for that if you started to work on it just before. I'll have a look at the change but I don't think it will pose a problem.
- Do not worry about `test_hf_api.py::TestSpaceAPIProduction` tests not passing. It's unrelated to this PR - I did to fix them separately

**Comment by tomaarsen** [comment]
Hello @Wauplin,
Thanks for the reply! I've made the suggested change using `-> "KerasModelHubMixin"`. Alternatively `-> KerasModelHubMixin` and `from __future__ import annotations` is also possible, but I went with the simpler one. 

I'll leave the CI complaints up to you for now :)

- Tom Aarsen

**Comment by Wauplin** [comment]
That was quick! 
I fixed the code formatting and pushed directly to your branch. Once the CI is green, I'll merge (green-ish since Space tests will fail :confused:)

**Review by Wauplin — APPROVED** [review]
Approved!

**Pull request merged**
