### PR TITLE
type of conflicting_files of DiscussionWDetails

### PR DESCRIPTION
**Pull request by ademait**
Related to #1830

### CODE REVIEW

**Comment by ademait** [comment]
Of course! @Wauplin done!

**Review by Wauplin — COMMENTED** [review]
Thanks for making the change @ademait! Looks good now :tada:

**Review by Wauplin — APPROVED** [review]

**Comment by Wauplin** [comment]
Failing tests are unrelated. I'm merging this now!

**Comment by Wauplin** [comment]
Oops, completely forgot to merge :see_no_evil:

**Pull request merged**
