### PR TITLE
`metadata_{load, save}`: ability to work on strings not files

### PR DESCRIPTION
**Pull request by julien-c**
oftentimes it's more convenient for me to work on strings (for instance in the context of opening PRs) than on files.

WDYT of this proposed methods?

### CODE REVIEW

**Review by adrinjalali — COMMENTED** [review]
An alternative (and IMO a better API) would be to accept `file` which can be a path or a file object, and then the user can simply pass `StringIO(mystring)` to the methods.

**Comment by julien-c** [comment]
Yes, good point – do people usually know `StringIO()` though? and it's just for the `load` case, not the `save` one, no?

**Comment by adrinjalali** [comment]
The same can apply to save functions. A user can choose to save the data in a StrinIO to do whatever they wish with it.

**Comment by nateraw** [comment]
This will be resolved with #940

**Comment by julien-c** [comment]
the line ending detection was incorporated into #949

**Comment by Wauplin** [comment]
This is completely solved by https://github.com/huggingface/huggingface_hub/pull/940 using @nateraw's templates right ? 
I'm closing this PR. If anyone sees something that has not been addressed, please re-open.

**Pull request closed without merging**
