### PR TITLE
Define cache errors in errors.py

### PR DESCRIPTION
**Pull request by 010kim**
Below is the list of descriptions for this PR.

1. Defined two errors (CacheNotFound, CorruptedCacheExcpetion) in errors.py
 - imported typing and pathlib package to keep the original definition of CacheNotFound

2. Adjusted the import paths in __init__.py

3. Removed the original definitions of the errors in _cache_manager.py
 - added "from huggingface_hub.errors import CacheNotFound, CorruptedCacheException" for API support

#2069

### CODE REVIEW

**Comment by 010kim** [comment]
@Wauplin Hello! I have a question about the definition for CacheNotFound class. I imported pathlib and typing packages in errors.py to keep the original definition of CacheNotFound. But I found in the previous comments of yours that you want to keep errors.py as simple as possible. Do you have any suggestions?

**Review by Wauplin — APPROVED** [review]
That's perfect, thanks!

> I imported pathlib and typing packages in errors.py to keep the original definition of CacheNotFound. But I found in the previous comments of yours that you want to keep errors.py as simple as possible. Do you have any suggestions?

What I meant in https://github.com/huggingface/huggingface_hub/issues/2069#issuecomment-2004549604 is that we should not add _logic_ to `errors.py` (for example, logic to raise an error from a failed `requests.Response`. However, it's perfectly fine to import standard modules. What would be annoying would be to have `from huggingface_hub.... import ...` in `errors.py` (which is unnecessary and can cause circular imports issues)

**Comment by Wauplin** [comment]
There seems to be styling issues. Could you install dev dependencies locally (see [here](https://github.com/huggingface/huggingface_hub/blob/e9cd695d7bd9e81b4eceb8f4da557a0cfa387b99/CONTRIBUTING.md?plain=1#L129)) and then run `make style` (see [here](https://github.com/huggingface/huggingface_hub/blob/e9cd695d7bd9e81b4eceb8f4da557a0cfa387b99/CONTRIBUTING.md?plain=1#L149)) to fix them. You can then test with `make quality` and commit the changes.

**Comment by 010kim** [comment]
I closed the PR to sync with the newest main branch. I will create another PR with the original fix.

**Comment by Wauplin** [comment]
It's also possible to update click on "update branch" on the PR page to get the latest update on your branch :wink:

**Pull request closed without merging**
