### PR TITLE
[InferenceClient] Add trust_env parameter in InferenceClient

### PR DESCRIPTION
**Pull request by morgandiverrez**
**Description**

Add trust_env parameter in InferenceClient

**Issue**
[[InferenceClient / langchain-HuggingFaceEndpoint] impossible to used Langchain HuggingFaceEndpoint whith trust_env=True #2522](https://github.com/huggingface/huggingface_hub/issues/2522)

### CODE REVIEW

**Comment by morgandiverrez** [comment]
hello, @Wauplin what do you think about this PR ?

**Comment by Wauplin** [comment]
Hi @morgandiverrez, sorry about the long delay. I wanted to check where exactly this is an issue in langchain integration. Can you pin-point the breaking line on GitHub? I just want to check the context of it

**Comment by morgandiverrez** [comment]
in this line : https://github.com/langchain-ai/langchain/blob/398718e1cb555e526bbf76ae163ded4c8d3cd1f8/libs/partners/huggingface/langchain_huggingface/llms/huggingface_endpoint.py#L216

**Comment by Wauplin** [comment]
Hi @morgandiverrez, thanks for the reference. First of all, sorry for the delay, I first wanted to check how to deal with this. I just opened a PR to fix things on the langchain side rather than here. See https://github.com/langchain-ai/langchain/pull/26378.

While this PR is correct, I prefer not to add parameters when it's not necessary. As mentioned in https://github.com/langchain-ai/langchain/pull/26378, I think that langchain integration should not assume a perfect match in supported kwargs for both clients. `trust_env` is a first issue but we might add new ones in the future that are only relevant to one or the other client but not both.

If the PR gets accepted, I would prefer to close this one without merging. Advanced users already have a way to configure `trust_env` in `huggingface_hub` globally (see [docs](https://huggingface.co/docs/huggingface_hub/package_reference/utilities#huggingface_hub.configure_http_backend)) for the sync client and giving the possibility here for a new argument might be misleading (+ create side effects since we are mutating the global session, not used only in `InferenceClient`). If you have any remarks and questions, please let me know :)

**Comment by Wauplin** [comment]
As explained above, I'll close this PR without merging in favor of https://github.com/langchain-ai/langchain/pull/26378 that just got merged.

**Pull request closed without merging**
