### PR TITLE
🗑 Deprecate `token` in read-only methods of `HfApi` in favor of `use_auth_token`

### PR DESCRIPTION
**Pull request by SBrandeis**
This PR deprecates the `token` argument in read-only methods of `HfApi` in favor of `use_auth_token`.

`use_auth_token` is more flexible as it allows not passing a token, whereas `token=None` fetches the token from `HfFolder`.

I personally prefer the semantics of `use_auth_token`, that I find very legible:
- `use_auth_token=False`
- `use_auth_token="token"`
- `use_auth_token=True`

cc @lhoestq

### CODE REVIEW

**Comment by adrinjalali** [comment]
I'd say adding `token=False` semantics is probably a better change. `token` is quite a crucial parameter and deprecating it would cause quite a bit of friction for downstream libraries. I'd say add the same semantics if you will, but to `token`.

Related: https://github.com/huggingface/huggingface_hub/issues/837

It would also be nice to pass token to let users pass token to a `HFApi` instance and not persist it: https://github.com/huggingface/huggingface_hub/issues/796

**Comment by lhoestq** [comment]
+1 for keeping `token`: the only case the `use_auth_token` semantic is useful is when passing `False`, which is definitely not the common case anyway - therefore renaming the parameter is maybe not worth it

**Review by julien-c — COMMENTED** [review]
i agree that it would be good to have consistency (and we shouldn't have introduced two different names in the first place)

I do not really mind whether it's called `use_auth_token` or `token`, though

**Comment by LysandreJik** [comment]
Agree with team members above on `token` rather than `use_auth_token` :)

**Comment by julien-c** [comment]
Thinking more on it, I think it's better to align everything to `use_auth_token` given it's used extensively in both `transformers` (794 occurences in 78 files) and `datasets` (198 occurences in 18 files)

I think the benefit of renaming to a "better" param name is too small compared to the breakage in downstream libraries

**Comment by LysandreJik** [comment]
Across libraries there seems to be a general tendency to have `token` for methods that will need a token in all cases (for example to push something to the hub), and `use_auth_token` in case a token might not be necessary.

To that end, if you feel strongly, I'm fine with going forward with this PR as it adds the `use_auth_token` argument to read only methods. However, in that case, we should go all in and remove the `token` from the signature and add it to a `kwargs`, and remove it from the documentation.

**Comment by SBrandeis** [comment]
cc @Wauplin

**Comment by Wauplin** [comment]
Coming a bit after the battle but I would also have been for a unique `token` parameter instead of both `token` and `use_auth_token` depending on the use case. Maybe I'm wrong but what I have in mind is that a typical user/dev will not really care about if a server needs a token or not. Worst case scenario, the server needs one and prompt an error to login once.

**Quick question**: is there a chance that a request that is today "public" become "private" (token required) in the future or the opposite ? If yes, having a single parameter name would avoid to handle a name change in `huggingface_hub` (+breaking changes, deprecate,...). I can't find an example yet but it doesn't seem that impossible.

In any case, I get the "it is as it is and vastly used already so let's keep both"-argument. It's a pretty strong argument in favor of this PR 😄 


**EDIT**(side note): what I found confusing in the current naming is that `token` and `auth_token` suggest that there is 2 types of tokens. At least that's what I first thought when reading the documentation. No big deal.

**Comment by Wauplin** [comment]
Just an update on this PR. I think there is kind of a consensus on moving forward to merge it. The rule will be "use `use_auth_token` for read-only methods and  `token` otherwise". It makes sense and shouldn't break too much external libraries.

That said, next steps are:
- [x] merge from `main` and try to resolve conflicts -> I did it from github
- [ ] fix the tests -> I think I broke them with the merge 
- [ ] deprecate `token` from v0.12
- [ ] expect deprecation in unittest + add new tests with `use_auth_token`
- [ ] make sure CI is fine

@SBrandeis if you'd like I can take care of it. I just need the permissions to push commits on your fork.
Let's get this done :)

**Pull request merged**
