### PR TITLE
Clarify what "More Resources" is by breaking it into its parts.

### PR DESCRIPTION
**Pull request by meg-huggingface**
This also helps distinguish it from the "More Information" section. It adds the jinja variables `demo`, `paper`, and `repo`. See discussion at:
https://huggingface.slack.com/archives/C025H22A3ND/p1669923069281609

### CODE REVIEW

**Comment by Wauplin** [comment]
Hi @meg-huggingface thanks for opening the PR. I have read the related slack conversation.

I am not against removing `More resources` without a deprecation cycle as it wouldn't break existing code. But if you don't mind could we still keep it as a `other` section ? Something like:
```
- **Repository:** {{ repo | default("[More Information Needed]", true)}}
- **Paper [optional]:** {{ paper | default("[More Information Needed]", true)}}
- **Demo [optional]:** {{ demo | default("[More Information Needed]", true)}}
{% if more_resources is defined and more_resources|length %}
- **Other [optional]:** {{ more_resources)}
{% endif %}
```
By default (and for most model cards) the "other" section will not be displayed. But if the field is already used by some users, the `more_resources` value will not be ignored. WDYT ? (cc @nateraw  as well).

Beside that, could you update [`./docs/source/how-to-model-cards.mdx` ](https://github.com/huggingface/huggingface_hub/blob/main/docs/source/how-to-model-cards.mdx#from-the-default-template) ? There are 2 occurrences of `more_resources` that need to be changed.

**Comment by EziOzoani** [comment]
For your last point @Wauplin do you mean this [doc](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/templates/modelcard_template.md) ??

**Comment by Wauplin** [comment]
> For your last point @Wauplin do you mean this [doc](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/templates/modelcard_template.md) ??

No I meant [this page](https://github.com/huggingface/huggingface_hub/blob/main/docs/source/how-to-model-cards.mdx#from-the-default-template) that is then rendered [here](https://huggingface.co/docs/huggingface_hub/how-to-model-cards#from-the-default-template). In the example in the documentation we use `more_resources=https://github.com/huggingface/huggingface_hub`. It should be updated to have `demo=...` for example (as `more_resources` is deprecated)

**Comment by meg-huggingface** [comment]
> Hi @meg-huggingface thanks for opening the PR. I have read the related slack conversation.
> 
> I am not against removing `More resources` without a deprecation cycle as it wouldn't break existing code. But if you don't mind could we still keep it as a `other` section ? Something like:
> 
> ```
> - **Repository:** {{ repo | default("[More Information Needed]", true)}}
> - **Paper [optional]:** {{ paper | default("[More Information Needed]", true)}}
> - **Demo [optional]:** {{ demo | default("[More Information Needed]", true)}}
> {% if more_resources is defined and more_resources|length %}
> - **Other [optional]:** {{ more_resources)}
> {% endif %}
> ```
> 
> By default (and for most model cards) the "other" section will not be displayed. But if the field is already used by some users, the `more_resources` value will not be ignored. WDYT ? (cc @nateraw as well).
> 
> Beside that, could you update [`./docs/source/how-to-model-cards.mdx` ](https://github.com/huggingface/huggingface_hub/blob/main/docs/source/how-to-model-cards.mdx#from-the-default-template) ? There are 2 occurrences of `more_resources` that need to be changed.

Agree on the Other, but I do wonder if anyone is actually using it? My impression is that these newer categories really aren't being used, so there isn't as much of an issue with changing (or removing). I'm happy to do the Other for now, but would like to ideally deprecate it if we find that tag hasn't been used yet.

**Review by Wauplin — APPROVED** [review]
Good to go !

**Pull request merged**
