### PR TITLE
Add test directions

### PR DESCRIPTION
**Pull request by muellerzr**
Adds a small markdown file that contains directions for running the test suite, since it took me a moment to get everything setup on my side.

### CODE REVIEW

**Comment by osanseviero** [comment]
If you do `export HUGGINGFACE_CO_STAGING=1` that will impact you later unless you revert it. 

One solution is to do
`HUGGINGFACE_CO_STAGING pytest -sv ./tests/` 
and then it should work.

**Comment by osanseviero** [comment]
I'm ok with going with this proposal in `/tests/README/md`, but we should consider creating a `CONTRIBUTING.md` for this.

**Comment by muellerzr** [comment]
Should be good to go now @osanseviero :)

**Review by osanseviero — APPROVED** [review]
Thanks for this!

**Pull request merged**
