### PR TITLE
added question-answering part for Bengali language

### PR DESCRIPTION
**Pull request by sagorbrur**
Hi,
I just added the question answering mapping part for the Bengali language.
Please check and if it is eligible for merging please merge.
thanks and regards
Sagor

### CODE REVIEW

**Comment by osanseviero** [comment]
Hi @sagorbrur!

Thank you for your contribution! Would it be possible to provide some examples with shorter, simpler contexts? You might find some inspiration in some of the English examples. 

Thank you once more!

**Comment by sagorbrur** [comment]
Hi @osanseviero ,
Thank you. 
There are no open-source QA datasets for Bengali except google's Tydiqa datasets.
The example I inserted here is actually from tydiqa dev datasets and these examples are benchmark examples.
If these large contexts make any problem for the model hub, I can change it.
Please let me know.
Regards

**Comment by osanseviero** [comment]
Thanks for explaining 🔥 

If these are benchmark examples, I think they are fine then. I'll let @LysandreJik take a final look and then we can merge :)

**Review by osanseviero — APPROVED** [review]

**Review by LysandreJik — APPROVED** [review]
LGTM!

**Comment by osanseviero** [comment]
Thank you for the contribution!

**Comment by sagorbrur** [comment]
Thanks to you all.

**Pull request merged**
