### PR TITLE
Raise after download if file size is not consistent

### PR DESCRIPTION
**Pull request by Wauplin**
Related to https://github.com/huggingface/huggingface_hub/issues/1396.

@guoyk93 reported an inconsistency while downloading a file from the Hub. Not sure what happened (couldn't reproduce it myself) but the very least we can do is to raise an error if the file size is not the expected one at the end of a download. Message suggests to use `force_download=True` and `resume_download=False` to be sure that any existing (corrupted) file will be overwritten.

Note: I didn't want to compute the checksum of the downloaded file as it's a time consuming process for the user (can take a few seconds for a huge file).

### CODE REVIEW

**Comment by guoyk93** [comment]
I think it might be more reasonable to delete the files with inconsistent sizes and download them again while loading models.

Checking the file size after downloading may not help, as this piece of logic may not run due to interruption

**Comment by Wauplin** [comment]
> Checking the file size after downloading may not help, as this piece of logic may not run due to interruption

Just to give you a hint on how it works internally, here is what we do:
1. Check if the file exists in the snapshot folder. If yes, return its path.
2. Check if the file exists in the blobs folder. If yes, create a symlink to the snapshot folder and return the snapshot filepath.
3. If none of the above, we download the file **to a temporary file**
    1. If `resume_download=True`, we look if there is a file under `.../path/to/cache/file.incomplete`. If yes, we continue the download from there. If not, we start the download from scratch.
    2. If `resume_download=False`, we start the download from scratch and store the data in a temporary file (e.g. `/tmp/tmp123456/...`).
4. Once the download is completed, we move it to the `blobs/` cache folder.
5. We create a symlink in the `snapshots/` folder and we return this path.

The file consistency check that I have added in this PR is done between step 3. and step 4., just before moving the temporary file to its real location in the cache. This means you cannot be in a state where the file is considered as "downloaded" in the cache but does not have the good size.

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks @Wauplin!

**Comment by Wauplin** [comment]
Cool, thanks for the review :)

**Pull request merged**
