### PR TITLE
Fix URL when uploading to proxy

### PR DESCRIPTION
**Pull request by Wauplin**
Follow-up PR after https://github.com/huggingface/huggingface_hub/pull/2155 to definitively fix https://github.com/huggingface/huggingface_hub/issues/2152. Thanks @livegoplayer for reporting the remaining issue in https://github.com/huggingface/huggingface_hub/issues/2152#issuecomment-2024984796. I made a mistake when trying the fix and my machine was still able to reach hf.co. This PR should settle the problem for good.

@livegoplayer would you mind trying again on your side? You can test it by installing `huggingface_hub` from this branch:

```
pip install git+https://github.com/huggingface/huggingface_hub@fix-url-for-good-when-using-procy
```

You testing scripts from https://github.com/huggingface/huggingface_hub/issues/2152#issuecomment-2024984796 looks good so normally upload should correctly work. Please let me know how it goes!

cc @padeoe vor visibility

### CODE REVIEW

**Comment by livegoplayer** [comment]
我又测试了一遍
image
image

image

**Comment by livegoplayer** [comment]
这是我的脚本地址
https://github.com/livegoplayer/scripts/blob/main/huggingface_io/test.py

**Comment by livegoplayer** [comment]
> The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_2167). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

**Comment by Wauplin** [comment]
Hi @livegoplayer I just pushed a (last?) fix: https://github.com/huggingface/huggingface_hub/pull/2167/commits/64abc0e735dcc315fbde1af6650e616f41617bdd. This was an oversight from my side. Just for the record:
- in https://github.com/huggingface/huggingface_hub/pull/2155 I fixed the return value when creating a repo
- which fixed uploading a regular file to the Hub
- in https://github.com/huggingface/huggingface_hub/pull/2167, I initially fixed the upload of a small LFS file
- finally, in https://github.com/huggingface/huggingface_hub/pull/2167/commits/64abc0e735dcc315fbde1af6650e616f41617bdd I fixed the upload of multipart LFS files

I previously forgot to distinguish the "single part" and "multi part" LFS workflows, that's why you got an error while I didn't. I only tried to upload a 1kb LFS file which has 1 step less than your 150MB file (since the 150Mb is split in chunks of 16MB). Anyway, I hope all issues are now fix. @livegoplayer could you retry and confirm? Thank you in advance :pray:

**Comment by livegoplayer** [comment]
> 你好@livegoplayer我刚刚推送了一个（最后一个？）修复：[64abc0e](https://github.com/huggingface/huggingface_hub/commit/64abc0e735dcc315fbde1af6650e616f41617bdd)。这是我的疏忽。仅供记录：
> 
> * 在[修复 HF_ENDPOINT 未正确处理 #2155](https://github.com/huggingface/huggingface_hub/pull/2155)中，我修复了创建存储库时的返回值
> * 修复了将常规文件上传到集线器的问题
> * 在[上传到代理时修复 URL  #2167](https://github.com/huggingface/huggingface_hub/pull/2167)中，我最初修复了一个小 LFS 文件的上传
> * 最后，在[64abc0e](https://github.com/huggingface/huggingface_hub/commit/64abc0e735dcc315fbde1af6650e616f41617bdd)中我修复了分段 LFS 文件的上传
> 
> 我之前忘记区分“单部分”和“多部分”LFS 工作流程，这就是为什么你收到错误而我没有。我只尝试上传一个 1kb LFS 文件，该文件比您的 150MB 文件少 1 步（因为 150Mb 被分成 16MB 的块）。无论如何，我希望所有问题现在都得到解决。@livegoplayer您可以重试并确认吗？提前谢谢🙏

我测试成功了，我上传了一个很多g的文件，并且成功了

**Comment by Wauplin** [comment]
Yay! :tada: 
Thanks for confirming! We should be good to go then :)

**Pull request merged**
