### PR TITLE
fix: Add `py.typed` marker file

### PR DESCRIPTION
**Pull request by sanmai-NL**
See: https://typing.readthedocs.io/en/latest/spec/distributing.html#packaging-type-information

### CODE REVIEW

**Comment by hanouticelina** [comment]
Hello @sanmai-NL, thanks for this PR. If I understand correctly, `py.typed` is a marker file used in python packages to indicate that the package supports type hints, It basically signals to type checkers that the package's type hints should be strictly checked, right?
is it possible that adding `py.typed` could break CI pipelines of packages that uses huggingface_hub if they have different/stricter type checker rules ?

**Comment by sanmai-NL** [comment]
@hanouticelina The strictness isn't controlled by this, just whether the package has type annotations at all.

**Comment by Wauplin** [comment]
Related to https://github.com/huggingface/huggingface_hub/issues/1662

**Comment by hanouticelina** [comment]
thanks for the context @Wauplin!
@sanmai-NL as explain in #1662, our `__init__.py` handles imports dynamically, re-adding a py.typed would require having and maintaining a static import system. For now, I'm leaning more towards keeping our current `__init__.py` as is and revisit this if we see more demand regarding that. I will close this PR but https://github.com/huggingface/huggingface_hub/issues/1662 is still open to track the community's interest!

thank you for your understanding 🤗

**Pull request closed without merging**
