### PR TITLE
Fix `list_accepted_access_requests` if grant user manually

### PR DESCRIPTION
**Pull request by Wauplin**
If a user is granted access to a repo without asking for it, their email address should not be shared to the repo owner. This has been enforced server-side by https://github.com/huggingface-internal/moon-landing/pull/10651 (internal). This PR fixes the client logic so that `email` is not required. Currently if one user from the list has been granted access, `list_accepted_access_requests` fails with a `KeyError`.

### CODE REVIEW

**Review by coyotte508 — COMMENTED** [review]
Note that theorically  someone can add a user and then reject them 

it's an edge case but...

**Comment by Wauplin** [comment]
> Note that theorically someone can add a user and then reject them
> it's an edge case but...

Docstring does not mention this use case but the logic would work. Client-side we have the exact same logic for the pending/accepted/rejected lists (since it's ~ the same endpoint server-side)

**Review by Pierrci — APPROVED** [review]
The logic LGTM :)

**Review by LysandreJik — APPROVED** [review]

**Review by julien-c — APPROVED** [review]

**Comment by Wauplin** [comment]
Yay! 3 approvals! :smile: Failed CI is unrelated so let's merge

**Pull request merged**
