### PR TITLE
Fix SafeTensorsInfo initialization

### PR DESCRIPTION
**Pull request by Wauplin**
Fix https://github.com/huggingface/huggingface_hub/issues/2186.

(failing CI is unrelated)

### CODE REVIEW

**Comment by Wauplin** [comment]
> How can I re-upload my model after a 24h training process die because of this bug?
I still have model folder in local.

[You can use the huggingface-cli to do that!](https://huggingface.co/docs/huggingface_hub/guides/cli#upload-an-entire-folder)

```bash
# Move to local folder
cd /path/to/local/checkpoints

# Upload local folder to model repo
huggingface-cli upload <REPO_ID>
```

**Review by Pierrci — APPROVED** [review]
lgtm :)

**Comment by Wauplin** [comment]
Thanks for the review :hugs:

**Review by julien-c — COMMENTED** [review]
lgtm

**Pull request merged**
