### PR TITLE
{upload|delete}_file: Remove client-side filename validation

### PR DESCRIPTION
**Pull request by SBrandeis**
Since there's already a check server-side

Related to https://github.com/huggingface/moon-landing/pull/2043

Also see https://huggingface.slack.com/archives/C02EMARJ65P/p1644250018894249?thread_ts=1644011058.534759&cid=C02EMARJ65P

cc @yjernite @Pierrci

### CODE REVIEW

**Review by coyotte508 — COMMENTED** [review]
LGTM!

**Review by LysandreJik — APPROVED** [review]
Looks good to me! It seems you have `black==22.1`, to which the CI hasn't been switched to yet, hence the failures. Should be switched to `black==2.1` at the end of the week.

**Review by Pierrci — APPROVED** [review]
Thanks @SBrandeis! 👍

**Comment by julien-c** [comment]
LGTM, thanks!

**Pull request merged**
