### PR TITLE
feat: 🎸 add HfApi.update_repo_settings to set a repo as gated

### PR DESCRIPTION
**Pull request by severo**
It also allows to disable/enable the discussions.

### CODE REVIEW

**Comment by julien-c** [comment]
not sure if there's a need to expose this programmatically to end users? 
WDYT @osanseviero @Wauplin?


If not, maybe keep it in your downstream code or in a helper

**Comment by severo** [comment]
OK

**Comment by osanseviero** [comment]
Probably there is not much interest in programmatically gating repos. Maybe we can revisit this PR if we get requests on this

**Comment by severo** [comment]
You're right, it's much simpler to keep it in my downstream code.

**Comment by cakiki** [comment]
I currently find myself needing to gate access to 498 datasets and feel it would be useful to expose that in HfApi, or maybe in the web interface on organization level (i.e. every dataset I publish in an org has to be gated with the following user agreement).

**Comment by severo** [comment]
Here is the code I'm using, in case it helps:

https://github.com/huggingface/datasets-server/blob/main/e2e/tests/fixtures/hub.py#L24-L92

**Comment by cakiki** [comment]
I sadly cannot access that file; any chance you could include it in a gist? :smiley_cat:

**Comment by severo** [comment]
Oh, sorry, here it is: https://gist.github.com/severo/0e9a1d8fb91f5ecb9c123ac48fbe6ea4

btw, we plan to opensource datasets-server in the next months.

**Comment by julien-c** [comment]
well... i stand corrected then! there is user demand for this!

Should we merge/add this feature then? WDYT?

**Comment by julien-c** [comment]
(though by "user", i mean @cakiki-level power user 😅)

**Pull request closed without merging**
