### PR TITLE
Support python 3.12

### PR DESCRIPTION
**Pull request by hanouticelina**
#### changes made
- run CI on Python 3.12.
- run `torch~=1.11` only on python 3.8.
- pin new supported version in `setup.py`.
- update documentation.

### CODE REVIEW

**Review by julien-c — COMMENTED** [review]
(btw python latest is 3.13 no? but not sure if the ML backends support it yet? though pytorch should work with latest python no?)

**Comment by hanouticelina** [comment]
@julien-c indeed, a stable version of python 3.13.0 was released last week https://www.python.org/downloads/release/python-3130/ but [tensorflow](https://www.tensorflow.org/install/pip) and [torch](https://pypi.org/project/torch/) are not supporting python 3.13 yet

**Comment by Wauplin** [comment]
Ahah true, I missed last year release :smile:

**Comment by hanouticelina** [comment]
The CI is green for python 3.12, let's bump the version to 3.13 and support it as well!

**Comment by hanouticelina** [comment]
issues with gradio support for python 3.13 ([gradio/issues/9696](https://github.com/gradio-app/gradio/issues/9696)) :(  we will only support python 3.12 for now and then bump to 3.13 once the issue is fixed.

**Review by Wauplin — APPROVED** [review]
Thanks for taking care of this!

**Pull request merged**
