### PR TITLE
Fix download from private renamed repo

### PR DESCRIPTION
**Pull request by Wauplin**
This PR fixes a bug when trying to download a regular file (non-LFS) from a private renamed repo. The problem came from the fact that:
1. renaming a repo induce a redirect
2. we were considering that any redirect means that we are downloading from a CDN
3. when we download from a CDN, we remove the `authorization` header since the URL is supposed to be signed
4. when making the actual GET call, the `authorization` header was not there + the url is not signed because it is still a relative redirect to huggingface.co

**=> this PR fixes this issue by keeping the `authorization` header when the redirected URL is from the same domain**

cc @LysandreJik @osanseviero who investigated the bug
cc @coyotte508 @XciD can you please review this PR as well? Just want to make sure I did not break anything (especially when downloading from a Space)

### CODE REVIEW

**Review by XciD — APPROVED** [review]

**Review by osanseviero — COMMENTED** [review]
Nice!

**Comment by Wauplin** [comment]
Thanks everyone for the quick review!

**Comment by Wauplin** [comment]
(failing tests are unrelated, closing this PR)

**Review by julien-c — COMMENTED** [review]
Agree with the fix

**Pull request merged**
