### PR TITLE
replace ANSI helper with termcolor

### PR DESCRIPTION
**Pull request by singingwolfboy**
There's no reason to define our own terminal color handler, when we can just use the [`termcolor`](https://github.com/termcolor/termcolor) library instead! It's better tested, better supported, and has more features -- including support for [the `NO_COLOR` env variable](https://no-color.org).

### CODE REVIEW

**Comment by Wauplin** [comment]
Hi @singingwolfboy, thanks for your work. The one good reason that we have this ANSI helper is to quite `huggingface_hub` package as minimal as possible when it comes to external dependencies. If we can save a dependency at the cost of 10 lines of code, we tend to do it. Of course it's always a tradeoff between reusing more powerful/tested/commonly used tools vs reinventing the wheel but in a case like this one, I am not sure we benefit too much from `termcolor`.

**Comment by singingwolfboy** [comment]
For my use-case, I need to call `huggingface-cli` from a script, and parse the result. Because of the way that this ANSI helper is coded, the terminal color escapes are included in the output, which is really annoying and difficult to parse. I need a way to tell `huggingface-cli` to _not_ output these color escapes, but this ANSI helper doesn't seem to have a way to do that.

`termcolor` is the most minimal dependency I could find that provides this color-based functionality, and as I said, it already respects the `NO_COLOR` environment variable. We could try to make the existing ANSI helper respect this environment variable as well, but to do so would probably make it more than 10 lines of code -- so at that point, we might as well go for the dependency instead. 😄

**Comment by Wauplin** [comment]
Out of curiosity, for what command do you need to call `huggingface-cli` from a script ? If it's for something like `huggingface-cli scan-cache` I would advice to directly use the python helper:

```py
from huggingface_hub import scan_cache_dir

hf_cache_info = scan_cache_dir(path)  # all the info is contained here
```
This would avoid you to have to parse the table in the first place, as the CLI is not adding any information besides `scan_cache_dir`.

Of course I'm fine with considering using `termcolor` if it makes sense.

**Comment by singingwolfboy** [comment]
> Out of curiosity, for what command do you need to call `huggingface-cli` from a script ?

For my specific use-case, I am trying to package this project for [Homebrew](https://brew.sh), and that requires a test to be sure that the installed package is working properly. [See this pull request](https://github.com/Homebrew/homebrew-core/pull/112767/files) -- specifically, the `test` section of `huggingface-cli.rb`.

More generally, text is the universal interface. Not every script is written in Python, and can import and use Python modules. But any script can run `huggingface-cli` as a subprocess and read the output. There will be other programs that want to do this as well -- particularly for scripts that run on CI, and upload/download data to Huggingface Hub.

**Comment by Wauplin** [comment]
Thanks again @singingwolfboy for making the change. I'm closing this PR and will merge the other one.

**Pull request closed without merging**
