### PR TITLE
Tidy up docs

### PR DESCRIPTION
**Pull request by stevhliu**
This PR adds some general maintenance to the docs:

- Links functions to the appropriate section in the API reference.
- Cleans up code outputs, formatting, images/fixes code examples in Searching the Hub.
- Adds `DatasetSearchArguments` and `ModelSearchArguments` to the API reference.

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks for this! Looks great from what I see 😄

**Review by LysandreJik — APPROVED** [review]
Thanks for working on this and for patching all of these issues!

I'll merge this PR right away as it's a much needed update. The only part which might need discussing is the links updates for images, which are moved from local files to remote files. I don't think this should be blocking as these images are currently not rendered correctly anyway. The discussion should happen at https://github.com/huggingface/huggingface_hub/issues/812.

Thanks @stevhliu!

**Comment by adrinjalali** [comment]
@osanseviero fetch this on the `hubs-docs` repo?

**Comment by osanseviero** [comment]
Why? This PR is for the library documentation. See https://huggingface.co/docs/huggingface_hub/how-to-downstream

**Comment by adrinjalali** [comment]
Fair, have we removed the docs that should be in the other repo from this repo?

**Pull request merged**
