### PR TITLE
Support custom kwargs for model card in save_pretrained

### PR DESCRIPTION
**Pull request by qubvel**
Hi!

There is an option to customize the model card for `Mixin`s, it would be great to support custom kwargs for a card also.

Here is an example:
```python
import torch
from huggingface_hub import PyTorchModelHubMixin


MODEL_CARD_TEMPLATE = """
---
# For reference on model card metadata, see the spec: https://github.com/huggingface/hub-docs/blob/main/modelcard.md?plain=1
# Doc / guide: https://huggingface.co/docs/hub/model-cards
{{ card_data }}
---
{{ custom_data }}
"""

class Model(torch.nn.Module, PyTorchModelHubMixin, model_card_template=MODEL_CARD_TEMPLATE):
    pass
    
model = Model()
model_card_kwargs = {"custom_data": "This is an awesome model..."}
model.save_pretrained("test-model", model_card_kwargs=model_card_kwargs, push_to_hub=True)
```

Generated readme:
```
---
tags:
- pytorch_model_hub_mixin
- model_hub_mixin
---
This is awesome model...
```

Let me know what you think about this feature! If it's OK, I can add the necessary tests.

### CODE REVIEW

**Comment by Wauplin** [comment]
The mixin currently have a set of very relevant model card metadata. For more customization, it's possible to overwrite the `_generate_model_card` method. This method allows more flexibility and access to model's values/config. It return a ModelCard object. For example:

```py
class Model(nn.Module, PytorchModelHubMixin):
    ...

    def _generate_model_card(self) -> ModelCard:
        card = super(self)._generate_model_card()
        card.data.custom_key = "custom value"
        return card
```

I'd prefer not to add too many features to the main way of defining tags/library_name/... to avoid complexity and promote this flexible method instead. WDYT?

**Comment by qubvel** [comment]
The feature is inspired by this [PR](https://github.com/qubvel/segmentation_models.pytorch/pull/876/files), as you may see I try to make it possible to pass a custom metrics dictionary and dataset name to be able to generate cards like this.
https://huggingface.co/qubvel-hf/oxford-pet-segmentation

```python
model.save_pretrained('./my_model', metrics={'accuracy': 0.95}, dataset='my_dataset')
```

You might want to pass arguments not at the time of model class creation, but at the time of model saving, for example when the model is trained. I overridden the `generate_mode_card()` method but I didn't find a way to pass any parameters from the `save_pretrained()` method. The only way I found is to set them as private attributes in `save_pretrained` and then remove them. 
https://github.com/qubvel/segmentation_models.pytorch/blob/3d6da1d74636873372c265f300862a6a6d01777d/segmentation_models_pytorch/base/hub_mixin.py#L107
Now it looks like a dirty hack :(

**Comment by qubvel** [comment]
@Wauplin thank you for the feedback! I will update the integration, would be cool to include this PR changes, to get rid of private attributes :)

> Could you add a small test in [test_hub_mixin_pytorch.py](https://github.com/huggingface/huggingface_hub/blob/4df59b4ed5d46dab2db58af4901b1a0a40dcfc6e/tests/test_hub_mixin_pytorch.py) with a new class that overwrites generate_model_card + pass data in save_pretrained and check you have the expected result. Thanks in advance!

Done! Please, have a look!

**Review by Wauplin — APPROVED** [review]
Amazing! Thanks for the prompt update :) Test is clean, CI is green, let's merge :tada:

**Comment by qubvel** [comment]
Thanks for the quick review and merge 🤗

**Pull request merged**
