### PR TITLE
Send Accept: image/png as header for image tasks

### PR DESCRIPTION
**Pull request by Wauplin**
cc @philschmid 

Tasks that expect an image to be returned by the server (i.e. image-to-image and text-to-image) must send `Accept: image/png` as header by default. This value can be overwritten by the user if needed. This PR fixes a bug happening with Inference Endpoints which returns a base64-encoded image in case Accept header is not set. This doesn't change anything for InferenceAPI calls.

**EDIT:** also fixes a bug in AsyncInferenceClient where headers set by the user where not taken into account.

**NOTE:** failing tests are unrelated

### CODE REVIEW

**Comment by StephenHodgson** [comment]
I also have not been able to get this to work myself. I think some tasks needed to be updated with the changes I made last month in https://github.com/huggingface/api-inference-community/pull/287.

**Comment by Wauplin** [comment]
@StephenHodgson If I understand correctly this PR and [the one](https://github.com/huggingface/api-inference-community/pull/287) you contributed last month are not exactly related. Here it is to fix InferenceClient to make it work with Inference Endpoints by force a default image mime type. But agree it could be safer to for a mime type for audio as well (though it can be done in another PR)

**Comment by StephenHodgson** [comment]
@Wauplin correct me if I'm wrong, but I'm pretty sure it uses the same infra, last I checked
 That's the main reason why I ended up making the PR there because I was trying to prove it out in my Unity client.

**Comment by Wauplin** [comment]
@StephenHodgson To clarify things:
- `InferenceAPI` is a service to quickly test and evaluate models hosted on the Hub. It's free of charge but only meant for quick prototyping. Docs are [here](https://huggingface.co/docs/api-inference/index). Part of the source code is public under [api-inference-community](https://github.com/huggingface/api-inference-community).
- `InferenceEndpoint` is a product to deploy models for production. This is a paid service to setup by the client (1 endpoint = 1 model = 1 GPU to pay). The entire implementation is private.
- `InferenceClient` is a client in `huggingface_hub` that can run inference with both `InferenceAPI` and `InferenceEndpoint`. The goal is to be compatible with both, and also endpoints hosted on other providers (AWS Sagemaker, Azure Endpoints,...). At the moment, we've more focused our attention on the HF solutions.

**Review by philschmid — APPROVED** [review]

**Pull request merged**
