### PR TITLE
Fix ReadTimeout when downloading file

### PR DESCRIPTION
**Pull request by Wauplin**
Related to internal [slack thread](https://huggingface.slack.com/archives/C01NE71C4F7/p1718102457171509) (private link) cc @amyeroberts 

Some tests started to fail in `transformers`. Might be related to an infra update or simply to a higher load in the CI. Failures are usually due to a `ReadTimeout` when downloading a file. There is already a retry mechanism when streaming the data from the server but not when making the first call. This PR fixes this by adding the same retry mechanism on the first call as well.

- https://app.circleci.com/pipelines/github/huggingface/transformers/95329/workflows/48549154-b3a0-4a77-8f99-6e797bf501f1/jobs/1254281
- https://app.circleci.com/pipelines/github/huggingface/transformers/95344/workflows/45291802-e7f0-42b2-8eb4-02d746170cea/jobs/1254538
- https://app.circleci.com/pipelines/github/huggingface/transformers/95363/workflows/964ce445-f68b-46b2-ae01-2bbbd9763f62/jobs/1254920
- https://app.circleci.com/pipelines/github/huggingface/transformers/95363/workflows/964ce445-f68b-46b2-ae01-2bbbd9763f62/jobs/1254919  

**Expected result:** no more random failures in the CI.

(note: code is quite duplicated but I did not found a way of factorizing it nicely. So let's say it's fine and better for readability)

### CODE REVIEW

**Review by julien-c — COMMENTED** [review]
isn't it masking the root issue?

**Review by amyeroberts — APPROVED** [review]
Thanks for adding! 

Agree with @julien-c that it means we might be maskng a wider issue. Somewhat selfishly, I'd be pro merging in atm as this is blocking for transformers PRs atm and requiring us to do lots of CI re-runs.

**Comment by Wauplin** [comment]
Infra/hub team is looking into it (see [slack thread](https://huggingface.slack.com/archives/C02EMARJ65P/p1718113652604269)). It should now be fixed server-side. @amyeroberts can you let me know if the problem persists in `transformers`'s CI? In the meantime, I'll convert this PR to draft and drop it if the fix is confirmed.

**Comment by amyeroberts** [comment]
@Wauplin It seems that we can close this - I haven't seen any read time outs in the past 1.5 days since the fix was handled by the infra team. Thanks for responding to this so quickly!

**Comment by Wauplin** [comment]
Great news! Thanks for following-up on this. I'm closing it but feel free to reach out if it ever happens again :)

**Pull request closed without merging**
