### PR TITLE
Main progress bar in snapshot download

### PR DESCRIPTION
**Pull request by Wauplin**
Fix https://github.com/huggingface/huggingface_hub/issues/1004.

While downloading, output looks like this:
```
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.20k/1.20k [00:00<00:00, 396kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.20k/1.20k [00:00<00:00, 396kB/s]
Fetching 9 files:  33%|█████████████████████████████████████████████████▋                                                                                                   | 3/9 [00:06<00:13,  2.33s/it]
Downloading:   4%|█████▊                                                                                                                                              | 34.7M/892M [00:04<01:57, 7.29MB/s]
```

And once snapshot download is finished: (both examples are not from the same repo)
```
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 440M/440M [01:06<00:00, 6.66MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 811k/811k [00:00<00:00, 3.84MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 210/210 [00:00<00:00, 86.2kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 269/269 [00:00<00:00, 73.8kB/s]
Fetching 7 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [01:09<00:00,  9.94s/it]
```

---

I am not sure which phrasing would be better here. The thing is, if you are doing a `snapshot_download` for a repo for which you already have some files, those files will not be fetched again. In the end, you end up with `Fetching 7 files` even though you are actually downloading only 4 files. Also the progress bar only shows the number of files to download, not the size of them. So the user still don't really know how much time they need to wait in total.

Still better than the existing so if you are happy with it, let's merge it :) (ping @philschmid)

### CODE REVIEW

**Comment by Wauplin** [comment]
Ping @stas00 as well.

**Review by LysandreJik — APPROVED** [review]
Nice, simple fix! I think it's fine to have the progress bar display work this way. It would be annoying if it showed a number of files to be downloaded inferior to the number of files that will actually be downloaded (saying it'll download 2 but really downloading 150), but this way around works well for me.

**Review by philschmid — APPROVED** [review]
LGTM! The only question is, should this be a default feature or something users can enable by passing an argument to `snapshot_download`?

**Review by osanseviero — APPROVED** [review]
Very cool, thanks!

**Comment by stas00** [comment]
Thank you for implementing this, @Wauplin and thank you, @philschmid for requesting it!

**Pull request merged**
