### PR TITLE
Add basic `upload_folder` feature

### PR DESCRIPTION
**Pull request by nateraw**
As discussed in #497, here's a quick draft of a basic `upload_folder` that will sequentially upload files within a folder. It's not ideal by any means, but it could get the job done for many simple cases.

### CODE REVIEW

**Comment by osanseviero** [comment]
Sorry, I just saw this is a draft PR. Let us know when we can review :hugs:

**Comment by julien-c** [comment]
i think the ability server-side to upload multiple files into one commit via the API is sufficiently near that maybe it doesn't make a lot of sense to include this in the library just yet – maybe more like sample code provided alongside (can even live in the repo)

Pinging @SBrandeis @coyotte508 @Pierrci for feedback on this though

**Comment by coyotte508** [comment]
Precision: There is an [ongoing PR](https://github.com/huggingface/moon-landing/pull/2803) that will support uploading multiple files. 

It's designed for upload of LFS files, so it only supports LFS files and text files. It doesn't support non-LFS binary files. And the total non-LFS payload allowed is currently 250kB (could be upped to a few MB).

The endpoints could be updated to have better support for non-LFS files, in another PR, but for now it's uploading one or multiple LFS files in a single commit.

**Comment by coyotte508** [comment]
Actually - The API will allow arbitrary commits (with a payload up to 20 MB, in addition to LFS data). So it should fit your needs :smile_cat:

**Comment by coyotte508** [comment]
It's up - the payload of the commit API has been upped to 100MB.

The endpoint is `/api/{models,datasets,spaces}/:namespace/:repo/commit/:branch`.

The payload looks like that in TypeScript (question mark = optional):

```ts
export interface CommitPayload {
	/** 
	 * List of added / edited files. Encoding is "utf-8" if not specified. Use "base64" for files 
	 * containing non-utf8 characters, or when in doubt.
	 */
	files?:        Array<{ content: string; path: string; encoding?: "utf-8" | "base64"; }>;
	deletedFiles?: Array<{ path: string; }>;
	/**
	 * New files to track with LFS, if not already tracked.
	 * Do this through the backend as QOL.
	 */
	lfsFiles?:     Array<{ path: string; algo: "sha256"; oid: string; }>;
	/** Commit summary */
	summary:       string;
	/** Commit description */
	description?:   string;
}
```

You do not need to manually edit the `.gitattributes` file when adding LFS files: just specifiy the filenames & hashes of lfs files in the `lfsFiles` field.

---

With this API, you need to preupload LFS files. It's basically using the native git lfs API: a [batch](https://github.com/git-lfs/git-lfs/blob/main/docs/api/batch.md) call first, followed by either a [basic](https://github.com/git-lfs/git-lfs/blob/main/docs/api/basic-transfers.md) upload or multipart upload (with our custom protocol). 

You can see the TS implementation [here](https://github.com/huggingface/moon-landing/commit/ecf3ca63057cd14c68ed07e7458a081b496d4eef#diff-527c7c9195e0de01a94e1fedbc0858e534c9e7e582e8e76f5fa8c300d018b2b4R278).

Definitely available on slack to talk about it.

---

Other note: a `preupload` endpoint has also been added, to know if a file should be uploaded through LFS or not, by sending the file path, file size and a sample of the data (512 bytes), as well as an optional `gitAttributes` file. You don't have to use it if local detection is preferrable ^^ cc @LysandreJik

**Comment by LysandreJik** [comment]
Thanks for the heads-up, @coyotte508! Will take a look at this and see how it could simplify the `upload_file`/`upload_folder` that @nateraw offers and simplify the #847.

**Comment by julien-c** [comment]
let's maybe close this PR as @SBrandeis is offering to work on this and the implem will be very different

Still would love @nateraw (and others) review though

**Pull request closed without merging**
