### PR TITLE
MNT add tabular task types to InferenceApi

### PR DESCRIPTION
**Pull request by adrinjalali**
We've moved to using `"tabular-{classification, regression}"` names for tasks, this reflects the change on the API backend side.

cc @Narsil @osanseviero

### CODE REVIEW

**Comment by LysandreJik** [comment]
We're about to release v0.9 with @Wauplin. Should this PR be in it?

**Comment by adrinjalali** [comment]
Yes please. Otherwise https://github.com/skops-dev/skops/pull/105 (hence next skops release) would need to wait till the next release.

**Comment by adrinjalali** [comment]
This can be tested as:

```python
from sklearn.datasets import load_breast_cancer

from huggingface_hub import InferenceApi


X, y = load_breast_cancer(return_X_y=True, as_frame=True)
res = InferenceApi(
    repo_id="scikit-learn/skops-blog-example", task="tabular-classification"
)(inputs={"data": X.head(10).to_dict(orient="list")})
res
```

**Comment by Wauplin** [comment]
@adrinjalali I am fine with approving/merging this now to have it in the 0.9 release however I am not sure to understand what it does. Is there a possibility that it breaks compatibility with another existing codebase ?

**Comment by adrinjalali** [comment]
This renaming has already happened in the backend, so even if it does break existing codebase, it has already done that :D But this is used mostly for sklearn integration and that front is happening these days and we don't have many models on the hub using it yet.

ref: https://github.com/huggingface/api-inference-community/pull/59

**Review by Wauplin — APPROVED** [review]

**Comment by adrinjalali** [comment]
Thanks 🙏🏼

**Pull request merged**
