### PR TITLE
New endpoint: `create_commits_on_pr`

### PR DESCRIPTION
**Pull request by Wauplin**
Step 2 of https://github.com/huggingface/huggingface_hub/issues/1352 (see https://github.com/huggingface/huggingface_hub/issues/1352#issuecomment-1452100232).

Here is my [test repo](https://huggingface.co/Wauplin/tmp_repo_snapshot_upload) with an [example of PR](https://huggingface.co/Wauplin/tmp_repo_snapshot_upload/discussions/16) where I pushed all the `huggingface_hub` source code to the repo. This is a toy example but it should work the same no matter the number and size of the files.

---
**EDIT:** I refactored the implementation / the description.

**High-level example:**
```py
from huggingface_hub import upload_folder

upload_folder(
    repo_id=repo_id,
    folder_path="path/to/folder",
    multi_commits=True,
    multi_commits_verbose=True,
    ignore_patterns="*__pycache__*",
    delete_patterns="*",
)
```
=> existing files are deleting and local folder is uploaded. Happens in multiple commits, pushed to a PR. PR is either merged (if `create_pr=False`) or not.

**Low-level example:**

```py
# Define low level operations
operations = [...] # list of CommitOperationAdd and CommitOperationDelete

# Split operations in commits
# Can be done manually or use a predefined strategy (based on max nb files/max upload size per commit) 
addition_commits, deletion_commits = plan_multi_commits(operations)
# Now we have 2 lists of commits. Additions and deletions are separated (deletions are pushed first).

# Create commits => will return the URL to the PR
api = HfApi()
api.create_commits_on_pr(
    repo_id=...,
    commit_message=...,
    addition_commits=addition_commits,
    deletion_commits=deletion_commits,
    merge_pr=False,
)
```

**How it works internally:**

1. Each commit contains only additions or only deletions. Deletions are pushed first and additions later. Order of operations is not guaranteed but shouldn't be a problem.
2. Each commit has a deterministic ID => the multi-commit has also a deterministic ID => persistent across re-runs
3. Create a PR with multi-commit ID in the name or retrieve an existing one.
4. List commits already pushed.
5. Push remaining commits. Each commit contains the commit ID to be recognized later.
6. In the meantime, PR description gets updated with the progress.
7. At the end, PR is set as "open for reviews" and merged automatically if `merge_pr=True`.

**TODO:**
- [ ] add unit tests
- [ ] add objects to the package reference
- [ ] adapt the existing upload guide

### CODE REVIEW

**Review by lhoestq — APPROVED** [review]
Love it !

**Comment by LysandreJik** [comment]
The code looks good to me @Wauplin, but I'll let @julien-c approve/reject it as [he might have opinions about opening PRs](https://github.com/huggingface/huggingface_hub/issues/1352#issuecomment-1438597516)

**Review by julien-c — COMMENTED** [review]
looks good to me from quick glance!

**Comment by Wauplin** [comment]
As a first start for this feature, I'll release it as "experimental" meaning that using it triggers a warning for the user ("we do not guarantee long-term support"). I'm doing so to ensure we have flexibility if we want to re-think this process.

**Pull request merged**
