### PR TITLE
Add an alias that makes dateutil optional.

### PR DESCRIPTION
**Pull request by Wauplin**
`python-dateutil` usage has been introduced by the Community API PR https://github.com/huggingface/huggingface_hub/pull/930. However, this adds an extra dependency to `huggingface_hub` which we want to avoid when possible. The dependency has not been formerly added to `setup.py` which was reported [in this thread](https://huggingface.slack.com/archives/C02V5EA0A95/p1660839367099929?thread_ts=1660827165.997349&cid=C02V5EA0A95) (internal link) when doing the 0.9 pre-release.

Since `dateutil` is only used to parse a UTC-isoformatted date string returned from the server, we can assume that we know which format to use to parse the date string. Given that, it is possible to build a weak parser using a pure python implementation.

That said, I am still quite undecided on how to proceed. I see multiple solutions:
1. Add `python-dateutil` as a dependency. It's straightforward but my understanding is we want to avoid 3rd-party libraries when only used for a "simple" use case.
2. Have a weak parser expecting `"%Y-%m-%dT%H:%M:%S.%fZ"` format. This works without any third-party dependency. Big drawback is that we are dependent on any change on the server. My expectation is that "it shouldn't happen" but if it happens it means we would need to do a hot-fix on all older versions of `huggingface_hub`.
3. The in-between solution: by default, `parse_datetime` will use `dateutil` if it's installed. Otherwise, it will default to the weak parser. In the future if the server response format changes, a `ValueError` will be raised with message `Please run "pip install huggingface_hub[dateutil]"` which seems less problematic than hot-fixing `huggingface_hub`. Drawback here is that I found it shaky to have a different parser depending on the installation.

For now I implemented solution 3. but I'd be very happy to know your opinion on it. If solution 1 or 2 or anything else is preferable, I don't mind changing it.

Ping @LysandreJik @adrinjalali @osanseviero since I guess you have more experience/are more opinionated on how to manage an open-source project. Ping also @SBrandeis @Pierrci working on moon-landing.

### CODE REVIEW

**Comment by adrinjalali** [comment]
yeah I'm not sure which one's the best option. I'd rather do either option 1 or 3. Not sure which one I prefer.

(you can also make codecov to wait for all tests before publishing the results by telling it how many updates it should wait for)

**Comment by Wauplin** [comment]
> yeah I'm not sure which one's the best option. I'd rather do either option 1 or 3. Not sure which one I prefer.

Thanks for the quick feedback. Let's see what others think, both 1. and 3. sound "not so good" and "not so bad" to me.

> (you can also make codecov to wait for all tests before publishing the results by telling it how many updates it should wait for)

Thanks for the tip, I should definitely look into this otherwise I'm already annoyed by it 🙄

**Comment by osanseviero** [comment]
Given this is a simple format, I'm inclined towards option 2. Server format should not change if we want to keep backwards compatibility. WDYT @SBrandeis?

**Comment by Pierrci** [comment]
+1 on @osanseviero pick of option 2, the date format returned by the server is very very very (very) unlikely to change.

**Comment by Wauplin** [comment]
> the date format returned by the server is very very very (very) unlikely to change.

Ok let's go for option 2 then. I made the change to remove any `dateutil` fallback.
PR review is welcomed :)

**Comment by Wauplin** [comment]
Side note: failing tests are not due to this PR in particular. I created a separate issue to discuss about it (see https://github.com/huggingface/huggingface_hub/issues/1002 and https://github.com/huggingface/moon-landing/issues/3695).

**Review by LysandreJik — APPROVED** [review]

**Comment by julien-c** [comment]
late to this convo but yes fully aligned with solution 2, and we can even add some tests in moon-landing CI to spec/guarantee it

**Pull request merged**
