### PR TITLE
`feature_extraction` allowing for `text: List[str]`

### PR DESCRIPTION
**Pull request by jamesbraza**
Fixes https://github.com/huggingface/huggingface_hub/issues/1745

### CODE REVIEW

**Comment by osanseviero** [comment]
Very nice, thanks for the PR!

**Comment by jamesbraza** [comment]
Ah I see, and thanks for the compliment on PR quality. I understand now that `InferenceClient` is not just an API wrapper, but actually only supports certain work streams.

I'm not quite onboard single-`str` only is better because:

- Since Hugging Face Inference API's requests are rate limited, one bulk transaction is better than many smaller transactions from a "free users getting best mileage" standpoint
- For the synchronous `InferenceClient`, one request with a bigger payload is faster than multiple requests with a smaller payload. Less boilerplate overall in the network packets, less established connections
    - Though the best is using `AsyncInferenceClient` and parallelizing many requests 🚀 

As far as future optimization of single-`str` only, I would say this already exists with TGI backend vs `transformers` backends. Devs just become aware that one route is optimized and another isn't. Though I do agree with you that learning that is an extra hassle.

Fwiw, LangChain actually uses the `List[str]` capability in its custom API wrapper, https://github.com/langchain-ai/langchain/blob/v0.0.315/libs/langchain/langchain/embeddings/huggingface.py#L323, so people do use this capability.

---

I don't actually care that much either, my main motivation for this was I use `List[str]` in my work-in-progress new addition to LlamaIndex: https://github.com/run-llama/llama_index/pull/8098/files#diff-3929ac166c73f28593444e39eb4135b61531dc6c6184b1a8f8486f4d4cedf344R238

I can just adjust my implementation there to center on `AsyncInferenceClient` for sending 1+ texts in parallel.

I leave it up to you, feel free to close this out

**Comment by jamesbraza** [comment]
One other point is, with `List[str]` when the strings have different token counts, the returned blob breaks `feature_extraction`'s `np.array(_bytes_to_dict(response), ...)` casting, because each embedding has a different size.  The test case I added here circumvented that by making sure the contained `str`s all have the same tokens.

So really, the return type of this function should be:

- `np.ndarray`: when passed `str`
- `List[np.ndarray]`: when passed `List[str]`

So to do this right, really the return type should be modified as well.  I am just going to close this out

**Comment by Wauplin** [comment]
Thanks for listing the advantages of enabling `List[str]`. I think it's good to remember them if we want to update the policy in the future :+1: Also agree that we should be sure return type is correct as well. About HTTP optimizations of batching the endpoint, I agree with you though I hope it'll not cause much issue even for free users

 Just for your info, if you do a `for txt in txts: client.feature_extraction(txt)` the SSL connection will be reused automatically. I still think it's best to use async for large inference as you suggested, but wanted to let you know :)

**Comment by jingfelix** [comment]
Given the discussions in https://github.com/huggingface/huggingface_hub/issues/2824 and https://github.com/huggingface/huggingface.js/pull/1166, I believe it's time we reconsider reopening this issue 👀

**Pull request closed without merging**
